import type { LineRoutesConfig } from "./types.js";
import * as line from "../corequery/lines/line-ids.js";
import * as stop from "../corequery/stops/stop-ids.js";
import * as tag from "../corequery/lines/service-tags.js";
import {
  withReversedRoute,
  withReversedRoutes,
} from "../utils/with-reversed-routes.js";
import { formalizeRouteStops } from "../utils/formalize-stops.js";
import { createCityLoopRoutes } from "../utils/city-loop.js";

export const lineRoutes: LineRoutesConfig = {
  [line.ALAMEIN]: createCityLoopRoutes("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HAWTHORN,
    stop.GLENFERRIE,
    stop.AUBURN,
    stop.CAMBERWELL,
    stop.RIVERSDALE,
    stop.WILLISON,
    stop.HARTWELL,
    stop.BURWOOD,
    stop.ASHBURTON,
    stop.ALAMEIN,
  ]),

  [line.BALLARAT]: withReversedRoutes([
    {
      color: "purple",
      stops: formalizeRouteStops([
        stop.SOUTHERN_CROSS,
        stop.FOOTSCRAY,
        stop.SUNSHINE,
        stop.ARDEER,
        stop.DEER_PARK,
        stop.CAROLINE_SPRINGS,
        stop.ROCKBANK,
        stop.COBBLEBANK,
        stop.MELTON,
        stop.BACCHUS_MARSH,
        stop.BALLAN,
        stop.BALLARAT,
        stop.WENDOUREE,
        stop.BEAUFORT,
        stop.ARARAT,
      ]),
      serviceTags: [tag.OUTBOUND],
    },
    {
      color: "purple",
      stops: formalizeRouteStops([
        stop.SOUTHERN_CROSS,
        stop.FOOTSCRAY,
        stop.SUNSHINE,
        stop.ARDEER,
        stop.DEER_PARK,
        stop.CAROLINE_SPRINGS,
        stop.ROCKBANK,
        stop.COBBLEBANK,
        stop.MELTON,
        stop.BACCHUS_MARSH,
        stop.BALLAN,
        stop.BALLARAT,
        stop.CRESWICK,
        stop.CLUNES,
        stop.TALBOT,
        stop.MARYBOROUGH,
      ]),
      serviceTags: [tag.OUTBOUND],
    },
  ]),

  [line.BELGRAVE]: createCityLoopRoutes("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HAWTHORN,
    stop.GLENFERRIE,
    stop.AUBURN,
    stop.CAMBERWELL,
    stop.EAST_CAMBERWELL,
    stop.CANTERBURY,
    stop.CHATHAM,
    stop.UNION,
    stop.BOX_HILL,
    stop.LABURNUM,
    stop.BLACKBURN,
    stop.NUNAWADING,
    stop.MITCHAM,
    stop.HEATHERDALE,
    stop.RINGWOOD,
    stop.HEATHMONT,
    stop.BAYSWATER,
    stop.BORONIA,
    stop.FERNTREE_GULLY,
    stop.UPPER_FERNTREE_GULLY,
    stop.UPWEY,
    stop.TECOMA,
    stop.BELGRAVE,
  ]),

  [line.BENDIGO]: withReversedRoutes([
    {
      color: "purple",
      stops: formalizeRouteStops([
        stop.SOUTHERN_CROSS,
        stop.FOOTSCRAY,
        stop.SUNSHINE,
        stop.WATERGARDENS,
        stop.SUNBURY,
        stop.CLARKEFIELD,
        stop.RIDDELLS_CREEK,
        stop.GISBORNE,
        stop.MACEDON,
        stop.WOODEND,
        stop.KYNETON,
        stop.MALMSBURY,
        stop.CASTLEMAINE,
        stop.KANGAROO_FLAT,
        stop.BENDIGO,
        stop.EPSOM,
        stop.HUNTLY,
        stop.GOORNONG,
        stop.ELMORE,
        stop.ROCHESTER,
        stop.ECHUCA,
      ]),
      serviceTags: [tag.OUTBOUND],
    },
    {
      color: "purple",
      stops: formalizeRouteStops([
        stop.SOUTHERN_CROSS,
        stop.FOOTSCRAY,
        stop.SUNSHINE,
        stop.WATERGARDENS,
        stop.SUNBURY,
        stop.CLARKEFIELD,
        stop.RIDDELLS_CREEK,
        stop.GISBORNE,
        stop.MACEDON,
        stop.WOODEND,
        stop.KYNETON,
        stop.MALMSBURY,
        stop.CASTLEMAINE,
        stop.KANGAROO_FLAT,
        stop.BENDIGO,
        stop.EAGLEHAWK,
        stop.RAYWOOD,
        stop.DINGEE,
        stop.PYRAMID,
        stop.KERANG,
        stop.SWAN_HILL,
      ]),
      serviceTags: [tag.OUTBOUND],
    },
  ]),

  [line.CITY_CIRCLE]: withReversedRoute({
    color: "red",
    stops: formalizeRouteStops([
      stop.FLINDERS_STREET,
      stop.SOUTHERN_CROSS,
      stop.FLAGSTAFF,
      stop.MELBOURNE_CENTRAL,
      stop.PARLIAMENT,
      stop.FLINDERS_STREET,
    ]),
    serviceTags: [tag.CITY_LOOP_CLOCKWISE, tag.VIA_CITY_LOOP],
  }),

  [line.CRAIGIEBURN]: createCityLoopRoutes("yellow", [
    stop.NORTH_MELBOURNE,
    stop.KENSINGTON,
    stop.NEWMARKET,
    stop.ASCOT_VALE,
    stop.MOONEE_PONDS,
    stop.ESSENDON,
    stop.GLENBERVIE,
    stop.STRATHMORE,
    stop.PASCOE_VALE,
    stop.OAK_PARK,
    stop.GLENROY,
    stop.JACANA,
    stop.BROADMEADOWS,
    stop.COOLAROO,
    stop.ROXBURGH_PARK,
    stop.CRAIGIEBURN,
  ]),

  [line.CRANBOURNE]: [
    ...withReversedRoute({
      color: "cyan",
      stops: formalizeRouteStops([
        stop.TOWN_HALL,
        stop.ANZAC,
        stop.HAWKSBURN,
        stop.TOORAK,
        stop.ARMADALE,
        stop.MALVERN,
        stop.CAULFIELD,
        stop.CARNEGIE,
        stop.MURRUMBEENA,
        stop.HUGHESDALE,
        stop.OAKLEIGH,
        stop.HUNTINGDALE,
        stop.CLAYTON,
        stop.WESTALL,
        stop.SPRINGVALE,
        stop.SANDOWN_PARK,
        stop.NOBLE_PARK,
        stop.YARRAMAN,
        stop.DANDENONG,
        stop.LYNBROOK,
        stop.MERINDA_PARK,
        stop.CRANBOURNE,
      ]),
      serviceTags: [tag.OUTBOUND],
    }),
    ...createCityLoopRoutes("cyan", [
      stop.RICHMOND,
      stop.SOUTH_YARRA,
      stop.HAWKSBURN,
      stop.TOORAK,
      stop.ARMADALE,
      stop.MALVERN,
      stop.CAULFIELD,
      stop.CARNEGIE,
      stop.MURRUMBEENA,
      stop.HUGHESDALE,
      stop.OAKLEIGH,
      stop.HUNTINGDALE,
      stop.CLAYTON,
      stop.WESTALL,
      stop.SPRINGVALE,
      stop.SANDOWN_PARK,
      stop.NOBLE_PARK,
      stop.YARRAMAN,
      stop.DANDENONG,
      stop.LYNBROOK,
      stop.MERINDA_PARK,
      stop.CRANBOURNE,
    ]),
  ],

  [line.FLEMINGTON_RACECOURSE]: createCityLoopRoutes("gray", [
    stop.NORTH_MELBOURNE,
    stop.KENSINGTON,
    stop.NEWMARKET,
    stop.SHOWGROUNDS,
    stop.FLEMINGTON_RACECOURSE,
  ]),

  [line.FRANKSTON]: createCityLoopRoutes("green", [
    stop.RICHMOND,
    stop.SOUTH_YARRA,
    stop.HAWKSBURN,
    stop.TOORAK,
    stop.ARMADALE,
    stop.MALVERN,
    stop.CAULFIELD,
    stop.GLEN_HUNTLY,
    stop.ORMOND,
    stop.MCKINNON,
    stop.BENTLEIGH,
    stop.PATTERSON,
    stop.MOORABBIN,
    stop.HIGHETT,
    stop.SOUTHLAND,
    stop.CHELTENHAM,
    stop.MENTONE,
    stop.PARKDALE,
    stop.MORDIALLOC,
    stop.ASPENDALE,
    stop.EDITHVALE,
    stop.CHELSEA,
    stop.BONBEACH,
    stop.CARRUM,
    stop.SEAFORD,
    stop.KANANOOK,
    stop.FRANKSTON,
  ]),

  [line.GEELONG]: withReversedRoute({
    color: "purple",
    stops: formalizeRouteStops([
      stop.SOUTHERN_CROSS,
      { stopId: stop.NORTH_MELBOURNE, collapseInStoppingPatterns: true },
      { stopId: stop.SOUTH_KENSINGTON, collapseInStoppingPatterns: true },
      stop.FOOTSCRAY,
      { stopId: stop.MIDDLE_FOOTSCRAY, collapseInStoppingPatterns: true },
      { stopId: stop.WEST_FOOTSCRAY, collapseInStoppingPatterns: true },
      { stopId: stop.TOTTENHAM, collapseInStoppingPatterns: true },
      stop.SUNSHINE,
      stop.ARDEER,
      stop.DEER_PARK,
      stop.TARNEIT,
      stop.WYNDHAM_VALE,
      stop.LITTLE_RIVER,
      stop.LARA,
      stop.CORIO,
      stop.NORTH_SHORE,
      stop.NORTH_GEELONG,
      stop.GEELONG,
      stop.SOUTH_GEELONG,
      stop.MARSHALL,
      stop.WAURN_PONDS,
      stop.WINCHELSEA,
      stop.BIRREGURRA,
      stop.COLAC,
      stop.CAMPERDOWN,
      stop.TERANG,
      stop.SHERWOOD_PARK,
      stop.WARRNAMBOOL,
    ]),
    serviceTags: [tag.OUTBOUND],
  }),

  [line.GIPPSLAND]: withReversedRoute({
    color: "purple",
    stops: formalizeRouteStops([
      stop.SOUTHERN_CROSS,
      stop.FLINDERS_STREET,
      stop.RICHMOND,
      { stopId: stop.SOUTH_YARRA, collapseInStoppingPatterns: true },
      { stopId: stop.HAWKSBURN, collapseInStoppingPatterns: true },
      { stopId: stop.TOORAK, collapseInStoppingPatterns: true },
      { stopId: stop.ARMADALE, collapseInStoppingPatterns: true },
      { stopId: stop.MALVERN, collapseInStoppingPatterns: true },
      stop.CAULFIELD,
      { stopId: stop.CARNEGIE, collapseInStoppingPatterns: true },
      { stopId: stop.MURRUMBEENA, collapseInStoppingPatterns: true },
      { stopId: stop.HUGHESDALE, collapseInStoppingPatterns: true },
      { stopId: stop.OAKLEIGH, collapseInStoppingPatterns: true },
      { stopId: stop.HUNTINGDALE, collapseInStoppingPatterns: true },
      stop.CLAYTON,
      { stopId: stop.WESTALL, collapseInStoppingPatterns: true },
      { stopId: stop.SPRINGVALE, collapseInStoppingPatterns: true },
      { stopId: stop.SANDOWN_PARK, collapseInStoppingPatterns: true },
      { stopId: stop.NOBLE_PARK, collapseInStoppingPatterns: true },
      { stopId: stop.YARRAMAN, collapseInStoppingPatterns: true },
      stop.DANDENONG,
      { stopId: stop.HALLAM, collapseInStoppingPatterns: true },
      { stopId: stop.NARRE_WARREN, collapseInStoppingPatterns: true },
      stop.BERWICK,
      { stopId: stop.BEACONSFIELD, collapseInStoppingPatterns: true },
      { stopId: stop.OFFICER, collapseInStoppingPatterns: true },
      { stopId: stop.CARDINIA_ROAD, collapseInStoppingPatterns: true },
      stop.PAKENHAM,
      { stopId: stop.EAST_PAKENHAM, collapseInStoppingPatterns: true },
      stop.NAR_NAR_GOON,
      stop.TYNONG,
      stop.GARFIELD,
      stop.BUNYIP,
      stop.LONGWARRY,
      stop.DROUIN,
      stop.WARRAGUL,
      stop.YARRAGON,
      stop.TRAFALGAR,
      stop.MOE,
      stop.MORWELL,
      stop.TRARALGON,
      stop.ROSEDALE,
      stop.SALE,
      stop.STRATFORD,
      stop.BAIRNSDALE,
    ]),
    serviceTags: [tag.OUTBOUND],
  }),

  [line.GLEN_WAVERLEY]: createCityLoopRoutes("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HEYINGTON,
    stop.KOOYONG,
    stop.TOORONGA,
    stop.GARDINER,
    stop.GLEN_IRIS,
    stop.DARLING,
    stop.EAST_MALVERN,
    stop.HOLMESGLEN,
    stop.JORDANVILLE,
    stop.MOUNT_WAVERLEY,
    stop.SYNDAL,
    stop.GLEN_WAVERLEY,
  ]),

  [line.HURSTBRIDGE]: createCityLoopRoutes("red", [
    stop.JOLIMONT,
    stop.WEST_RICHMOND,
    stop.NORTH_RICHMOND,
    stop.COLLINGWOOD,
    stop.VICTORIA_PARK,
    stop.CLIFTON_HILL,
    stop.WESTGARTH,
    stop.DENNIS,
    stop.FAIRFIELD,
    stop.ALPHINGTON,
    stop.DAREBIN,
    stop.IVANHOE,
    stop.EAGLEMONT,
    stop.HEIDELBERG,
    stop.ROSANNA,
    stop.MACLEOD,
    stop.WATSONIA,
    stop.GREENSBOROUGH,
    stop.MONTMORENCY,
    stop.ELTHAM,
    stop.DIAMOND_CREEK,
    stop.WATTLE_GLEN,
    stop.HURSTBRIDGE,
  ]),

  [line.LILYDALE]: createCityLoopRoutes("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HAWTHORN,
    stop.GLENFERRIE,
    stop.AUBURN,
    stop.CAMBERWELL,
    stop.EAST_CAMBERWELL,
    stop.CANTERBURY,
    stop.CHATHAM,
    stop.UNION,
    stop.BOX_HILL,
    stop.LABURNUM,
    stop.BLACKBURN,
    stop.NUNAWADING,
    stop.MITCHAM,
    stop.HEATHERDALE,
    stop.RINGWOOD,
    stop.RINGWOOD_EAST,
    stop.CROYDON,
    stop.MOOROOLBARK,
    stop.LILYDALE,
  ]),

  [line.MERNDA]: createCityLoopRoutes("red", [
    stop.JOLIMONT,
    stop.WEST_RICHMOND,
    stop.NORTH_RICHMOND,
    stop.COLLINGWOOD,
    stop.VICTORIA_PARK,
    stop.CLIFTON_HILL,
    stop.RUSHALL,
    stop.MERRI,
    stop.NORTHCOTE,
    stop.CROXTON,
    stop.THORNBURY,
    stop.BELL,
    stop.PRESTON,
    stop.REGENT,
    stop.RESERVOIR,
    stop.RUTHVEN,
    stop.KEON_PARK,
    stop.THOMASTOWN,
    stop.LALOR,
    stop.EPPING,
    stop.SOUTH_MORANG,
    stop.MIDDLE_GORGE,
    stop.HAWKSTOWE,
    stop.MERNDA,
  ]),

  [line.PAKENHAM]: [
    ...withReversedRoute({
      color: "cyan",
      stops: formalizeRouteStops([
        stop.TOWN_HALL,
        stop.ANZAC,
        stop.HAWKSBURN,
        stop.TOORAK,
        stop.ARMADALE,
        stop.MALVERN,
        stop.CAULFIELD,
        stop.CARNEGIE,
        stop.MURRUMBEENA,
        stop.HUGHESDALE,
        stop.OAKLEIGH,
        stop.HUNTINGDALE,
        stop.CLAYTON,
        stop.WESTALL,
        stop.SPRINGVALE,
        stop.SANDOWN_PARK,
        stop.NOBLE_PARK,
        stop.YARRAMAN,
        stop.DANDENONG,
        stop.HALLAM,
        stop.NARRE_WARREN,
        stop.BERWICK,
        stop.BEACONSFIELD,
        stop.OFFICER,
        stop.CARDINIA_ROAD,
        stop.PAKENHAM,
        stop.EAST_PAKENHAM,
      ]),
      serviceTags: [tag.OUTBOUND],
    }),
    ...createCityLoopRoutes("cyan", [
      stop.RICHMOND,
      stop.SOUTH_YARRA,
      stop.HAWKSBURN,
      stop.TOORAK,
      stop.ARMADALE,
      stop.MALVERN,
      stop.CAULFIELD,
      stop.CARNEGIE,
      stop.MURRUMBEENA,
      stop.HUGHESDALE,
      stop.OAKLEIGH,
      stop.HUNTINGDALE,
      stop.CLAYTON,
      stop.WESTALL,
      stop.SPRINGVALE,
      stop.SANDOWN_PARK,
      stop.NOBLE_PARK,
      stop.YARRAMAN,
      stop.DANDENONG,
      stop.HALLAM,
      stop.NARRE_WARREN,
      stop.BERWICK,
      stop.BEACONSFIELD,
      stop.OFFICER,
      stop.CARDINIA_ROAD,
      stop.PAKENHAM,
      stop.EAST_PAKENHAM,
    ]),
  ],

  [line.SANDRINGHAM]: withReversedRoute({
    color: "pink",
    stops: formalizeRouteStops([
      stop.FLINDERS_STREET,
      stop.RICHMOND,
      stop.SOUTH_YARRA,
      stop.PRAHRAN,
      stop.WINDSOR,
      stop.BALACLAVA,
      stop.RIPPONLEA,
      stop.ELSTERNWICK,
      stop.GARDENVALE,
      stop.NORTH_BRIGHTON,
      stop.MIDDLE_BRIGHTON,
      stop.BRIGHTON_BEACH,
      stop.HAMPTON,
      stop.SANDRINGHAM,
    ]),
    serviceTags: [tag.OUTBOUND],
  }),

  [line.SEYMOUR]: withReversedRoutes([
    {
      color: "purple",
      stops: formalizeRouteStops([
        stop.SOUTHERN_CROSS,
        stop.NORTH_MELBOURNE,
        stop.ESSENDON,
        stop.BROADMEADOWS,
        stop.CRAIGIEBURN,
        stop.DONNYBROOK,
        stop.WALLAN,
        stop.HEATHCOTE_JUNCTION,
        stop.WANDONG,
        stop.KILMORE_EAST,
        stop.BROADFORD,
        stop.TALLAROOK,
        stop.SEYMOUR,
        stop.AVENEL,
        stop.EUROA,
        stop.VIOLET_TOWN,
        stop.BENALLA,
        stop.WANGARATTA,
        stop.SPRINGHURST,
        stop.CHILTERN,
        stop.WODONGA,
        stop.ALBURY,
      ]),
      serviceTags: [tag.OUTBOUND],
    },
    {
      color: "purple",
      stops: formalizeRouteStops([
        stop.SOUTHERN_CROSS,
        stop.NORTH_MELBOURNE,
        stop.ESSENDON,
        stop.BROADMEADOWS,
        stop.CRAIGIEBURN,
        stop.DONNYBROOK,
        stop.WALLAN,
        stop.HEATHCOTE_JUNCTION,
        stop.WANDONG,
        stop.KILMORE_EAST,
        stop.BROADFORD,
        stop.TALLAROOK,
        stop.SEYMOUR,
        stop.NAGAMBIE,
        stop.MURCHISON_EAST,
        stop.MOOROOPNA,
        stop.SHEPPARTON,
      ]),
      serviceTags: [tag.OUTBOUND],
    },
  ]),

  [line.STONY_POINT]: withReversedRoute({
    color: "green",
    stops: formalizeRouteStops([
      stop.FRANKSTON,
      stop.LEAWARRA,
      stop.BAXTER,
      stop.SOMERVILLE,
      stop.TYABB,
      stop.HASTINGS,
      stop.BITTERN,
      stop.MORRADOO,
      stop.CRIB_POINT,
      stop.STONY_POINT,
    ]),
    serviceTags: [tag.OUTBOUND],
  }),

  [line.SUNBURY]: [
    ...withReversedRoute({
      color: "cyan",
      stops: formalizeRouteStops([
        stop.TOWN_HALL,
        stop.STATE_LIBRARY,
        stop.PARKVILLE,
        stop.ARDEN,
        stop.FOOTSCRAY,
        stop.MIDDLE_FOOTSCRAY,
        stop.WEST_FOOTSCRAY,
        stop.TOTTENHAM,
        stop.SUNSHINE,
        stop.ALBION,
        stop.GINIFER,
        stop.ST_ALBANS,
        stop.KEILOR_PLAINS,
        stop.WATERGARDENS,
        stop.DIGGERS_REST,
        stop.SUNBURY,
      ]),
      serviceTags: [tag.OUTBOUND],
    }),
    ...createCityLoopRoutes("cyan", [
      stop.NORTH_MELBOURNE,
      stop.SOUTH_KENSINGTON,
      stop.FOOTSCRAY,
      stop.MIDDLE_FOOTSCRAY,
      stop.WEST_FOOTSCRAY,
      stop.TOTTENHAM,
      stop.SUNSHINE,
      stop.ALBION,
      stop.GINIFER,
      stop.ST_ALBANS,
      stop.KEILOR_PLAINS,
      stop.WATERGARDENS,
      stop.DIGGERS_REST,
      stop.SUNBURY,
    ]),
  ],

  [line.UPFIELD]: createCityLoopRoutes("yellow", [
    stop.NORTH_MELBOURNE,
    stop.MACAULAY,
    stop.FLEMINGTON_BRIDGE,
    stop.ROYAL_PARK,
    stop.JEWELL,
    stop.BRUNSWICK,
    stop.ANSTEY,
    stop.MORELAND,
    stop.COBURG,
    stop.BATMAN,
    stop.MERLYNSTON,
    stop.FAWKNER,
    stop.GOWRIE,
    stop.UPFIELD,
  ]),

  [line.WERRIBEE]: withReversedRoute({
    color: "pink",
    stops: formalizeRouteStops([
      stop.FLINDERS_STREET,
      stop.SOUTHERN_CROSS,
      stop.NORTH_MELBOURNE,
      stop.SOUTH_KENSINGTON,
      stop.FOOTSCRAY,
      stop.SEDDON,
      stop.YARRAVILLE,
      stop.SPOTSWOOD,
      stop.NEWPORT,
      stop.SEAHOLME,
      stop.ALTONA,
      stop.WESTONA,
      stop.LAVERTON,
      stop.AIRCRAFT,
      stop.WILLIAMS_LANDING,
      stop.HOPPERS_CROSSING,
      stop.WERRIBEE,
    ]),
    serviceTags: [tag.OUTBOUND],
  }),

  [line.WILLIAMSTOWN]: withReversedRoute({
    color: "pink",
    stops: formalizeRouteStops([
      stop.FLINDERS_STREET,
      stop.SOUTHERN_CROSS,
      stop.NORTH_MELBOURNE,
      stop.SOUTH_KENSINGTON,
      stop.FOOTSCRAY,
      stop.SEDDON,
      stop.YARRAVILLE,
      stop.SPOTSWOOD,
      stop.NEWPORT,
      stop.NORTH_WILLIAMSTOWN,
      stop.WILLIAMSTOWN_BEACH,
      stop.WILLIAMSTOWN,
    ]),
    serviceTags: [tag.OUTBOUND],
  }),
};
