import { type LineConfig } from "corequery";
import * as line from "./line-ids.js";
import * as tag from "./line-tags.js";
import * as stop from "../stops/stop-ids.js";
import {
  createCityLoopDiagram,
  createLinearDiagram,
} from "../../utils/diagram.js";
import { formalizeDiagramStops } from "../../utils/formalize-stops.js";

export const ALAMEIN: LineConfig = {
  id: line.ALAMEIN,
  name: "Alamein",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "alamein",
  color: "blue",
  diagram: createCityLoopDiagram("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HAWTHORN,
    stop.GLENFERRIE,
    stop.AUBURN,
    stop.CAMBERWELL,
    stop.RIVERSDALE,
    stop.WILLISON,
    stop.HARTWELL,
    stop.BURWOOD,
    stop.ASHBURTON,
    stop.ALAMEIN,
  ]),
};

export const BALLARAT: LineConfig = {
  id: line.BALLARAT,
  name: "Ballarat",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "ballarat",
  color: "purple",
  diagram: {
    entries: [
      {
        name: null,
        color: "purple",
        shape: {
          type: "branch",
          commonStops: formalizeDiagramStops([
            stop.SOUTHERN_CROSS,
            stop.FOOTSCRAY,
            stop.SUNSHINE,
            stop.ARDEER,
            stop.DEER_PARK,
            stop.CAROLINE_SPRINGS,
            stop.ROCKBANK,
            stop.COBBLEBANK,
            stop.MELTON,
            stop.BACCHUS_MARSH,
            stop.BALLAN,
            stop.BALLARAT,
          ]),
          branchAStops: formalizeDiagramStops([
            stop.WENDOUREE,
            stop.BEAUFORT,
            stop.ARARAT,
          ]),
          branchBStops: formalizeDiagramStops([
            stop.CRESWICK,
            stop.CLUNES,
            stop.TALBOT,
            stop.MARYBOROUGH,
          ]),
        },
      },
    ],
  },
};

export const BELGRAVE: LineConfig = {
  id: line.BELGRAVE,
  name: "Belgrave",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "belgrave",
  color: "blue",
  diagram: createCityLoopDiagram("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HAWTHORN,
    stop.GLENFERRIE,
    stop.AUBURN,
    stop.CAMBERWELL,
    stop.EAST_CAMBERWELL,
    stop.CANTERBURY,
    stop.CHATHAM,
    stop.UNION,
    stop.BOX_HILL,
    stop.LABURNUM,
    stop.BLACKBURN,
    stop.NUNAWADING,
    stop.MITCHAM,
    stop.HEATHERDALE,
    stop.RINGWOOD,
    stop.HEATHMONT,
    stop.BAYSWATER,
    stop.BORONIA,
    stop.FERNTREE_GULLY,
    stop.UPPER_FERNTREE_GULLY,
    stop.UPWEY,
    stop.TECOMA,
    stop.BELGRAVE,
  ]),
};

export const BENDIGO: LineConfig = {
  id: line.BENDIGO,
  name: "Bendigo",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "bendigo",
  color: "purple",
  diagram: {
    entries: [
      {
        name: null,
        color: "purple",
        shape: {
          type: "branch",
          commonStops: formalizeDiagramStops([
            stop.SOUTHERN_CROSS,
            stop.FOOTSCRAY,
            stop.SUNSHINE,
            stop.WATERGARDENS,
            stop.SUNBURY,
            stop.CLARKEFIELD,
            stop.RIDDELLS_CREEK,
            stop.GISBORNE,
            stop.MACEDON,
            stop.WOODEND,
            stop.KYNETON,
            stop.MALMSBURY,
            stop.CASTLEMAINE,
            stop.KANGAROO_FLAT,
            stop.BENDIGO,
          ]),
          branchAStops: formalizeDiagramStops([
            stop.EPSOM,
            stop.HUNTLY,
            stop.GOORNONG,
            stop.ELMORE,
            stop.ROCHESTER,
            stop.ECHUCA,
          ]),
          branchBStops: formalizeDiagramStops([
            stop.EAGLEHAWK,
            stop.RAYWOOD,
            stop.DINGEE,
            stop.PYRAMID,
            stop.KERANG,
            stop.SWAN_HILL,
          ]),
        },
      },
    ],
  },
};

export const CITY_CIRCLE: LineConfig = {
  id: line.CITY_CIRCLE,
  name: "City Circle",
  code: null,
  tags: [tag.SUBURBAN, tag.DISRUPTIONS_ONLY, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "citycircle",
  color: "red",
  diagram: {
    entries: [
      {
        name: null,
        color: "red",
        shape: {
          type: "loop",
          loopLeftStops: [
            { type: "regular", stopId: stop.SOUTHERN_CROSS },
            { type: "regular", stopId: stop.FLINDERS_STREET },
          ],
          loopRightStops: [
            { type: "regular", stopId: stop.FLAGSTAFF },
            { type: "regular", stopId: stop.MELBOURNE_CENTRAL },
            { type: "regular", stopId: stop.PARLIAMENT },
          ],
          mainStops: [],
        },
      },
    ],
  },
};

export const CRAIGIEBURN: LineConfig = {
  id: line.CRAIGIEBURN,
  name: "Craigieburn",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "craigieburn",
  color: "yellow",
  diagram: createCityLoopDiagram("yellow", [
    stop.NORTH_MELBOURNE,
    stop.KENSINGTON,
    stop.NEWMARKET,
    stop.ASCOT_VALE,
    stop.MOONEE_PONDS,
    stop.ESSENDON,
    stop.GLENBERVIE,
    stop.STRATHMORE,
    stop.PASCOE_VALE,
    stop.OAK_PARK,
    stop.GLENROY,
    stop.JACANA,
    stop.BROADMEADOWS,
    stop.COOLAROO,
    stop.ROXBURGH_PARK,
    stop.CRAIGIEBURN,
  ]),
};

export const CRANBOURNE: LineConfig = {
  id: line.CRANBOURNE,
  name: "Cranbourne",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "cranbourne",
  color: "cyan",
  diagram: createLinearDiagram("cyan", [
    stop.TOWN_HALL,
    stop.ANZAC,
    { stopId: stop.HAWKSBURN, type: "always-express" },
    { stopId: stop.TOORAK, type: "always-express" },
    { stopId: stop.ARMADALE, type: "always-express" },
    stop.MALVERN,
    stop.CAULFIELD,
    stop.CARNEGIE,
    stop.MURRUMBEENA,
    stop.HUGHESDALE,
    stop.OAKLEIGH,
    stop.HUNTINGDALE,
    stop.CLAYTON,
    stop.WESTALL,
    stop.SPRINGVALE,
    stop.SANDOWN_PARK,
    stop.NOBLE_PARK,
    stop.YARRAMAN,
    stop.DANDENONG,
    stop.LYNBROOK,
    stop.MERINDA_PARK,
    stop.CRANBOURNE,
  ]),
};

export const FLEMINGTON_RACECOURSE: LineConfig = {
  id: line.FLEMINGTON_RACECOURSE,
  name: "Flemington Racecourse",
  code: null,
  tags: [tag.SUBURBAN, tag.SPECIAL_EVENTS_ONLY, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "flemingtonracecourse",
  color: "gray",
  diagram: createLinearDiagram("gray", [
    stop.FLINDERS_STREET,
    stop.SOUTHERN_CROSS,
    stop.NORTH_MELBOURNE,
    { stopId: stop.KENSINGTON, type: "always-express" },
    { stopId: stop.NEWMARKET, type: "always-express" },
    stop.SHOWGROUNDS,
    stop.FLEMINGTON_RACECOURSE,
  ]),
};

export const FRANKSTON: LineConfig = {
  id: line.FRANKSTON,
  name: "Frankston",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "frankston",
  color: "green",
  diagram: createCityLoopDiagram("green", [
    stop.RICHMOND,
    stop.SOUTH_YARRA,
    stop.HAWKSBURN,
    stop.TOORAK,
    stop.ARMADALE,
    stop.MALVERN,
    stop.CAULFIELD,
    stop.GLEN_HUNTLY,
    stop.ORMOND,
    stop.MCKINNON,
    stop.BENTLEIGH,
    stop.PATTERSON,
    stop.MOORABBIN,
    stop.HIGHETT,
    stop.SOUTHLAND,
    stop.CHELTENHAM,
    stop.MENTONE,
    stop.PARKDALE,
    stop.MORDIALLOC,
    stop.ASPENDALE,
    stop.EDITHVALE,
    stop.CHELSEA,
    stop.BONBEACH,
    stop.CARRUM,
    stop.SEAFORD,
    stop.KANANOOK,
    stop.FRANKSTON,
  ]),
};

export const GEELONG: LineConfig = {
  id: line.GEELONG,
  name: "Geelong",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "geelong",
  color: "purple",
  diagram: createLinearDiagram("purple", [
    stop.SOUTHERN_CROSS,
    stop.FOOTSCRAY,
    stop.SUNSHINE,
    { stopId: stop.ARDEER, type: "always-express" },
    stop.DEER_PARK,
    stop.TARNEIT,
    stop.WYNDHAM_VALE,
    stop.LITTLE_RIVER,
    stop.LARA,
    stop.CORIO,
    stop.NORTH_SHORE,
    stop.NORTH_GEELONG,
    stop.GEELONG,
    stop.SOUTH_GEELONG,
    stop.MARSHALL,
    stop.WAURN_PONDS,
    stop.WINCHELSEA,
    stop.BIRREGURRA,
    stop.COLAC,
    stop.CAMPERDOWN,
    stop.TERANG,
    stop.SHERWOOD_PARK,
    stop.WARRNAMBOOL,
  ]),
};

export const GIPPSLAND: LineConfig = {
  id: line.GIPPSLAND,
  name: "Gippsland",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "gippsland",
  color: "purple",
  diagram: createLinearDiagram("purple", [
    stop.SOUTHERN_CROSS,
    stop.FLINDERS_STREET,
    stop.RICHMOND,
    stop.CAULFIELD,
    stop.CLAYTON,
    stop.DANDENONG,
    stop.BERWICK,
    stop.PAKENHAM,
    stop.NAR_NAR_GOON,
    stop.TYNONG,
    stop.GARFIELD,
    stop.BUNYIP,
    stop.LONGWARRY,
    stop.DROUIN,
    stop.WARRAGUL,
    stop.YARRAGON,
    stop.TRAFALGAR,
    stop.MOE,
    stop.MORWELL,
    stop.TRARALGON,
    stop.ROSEDALE,
    stop.SALE,
    stop.STRATFORD,
    stop.BAIRNSDALE,
  ]),
};

export const GLEN_WAVERLEY: LineConfig = {
  id: line.GLEN_WAVERLEY,
  name: "Glen Waverley",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "glenwaverley",
  color: "blue",
  diagram: createCityLoopDiagram("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HEYINGTON,
    stop.KOOYONG,
    stop.TOORONGA,
    stop.GARDINER,
    stop.GLEN_IRIS,
    stop.DARLING,
    stop.EAST_MALVERN,
    stop.HOLMESGLEN,
    stop.JORDANVILLE,
    stop.MOUNT_WAVERLEY,
    stop.SYNDAL,
    stop.GLEN_WAVERLEY,
  ]),
};

export const HURSTBRIDGE: LineConfig = {
  id: line.HURSTBRIDGE,
  name: "Hurstbridge",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "hurstbridge",
  color: "red",
  diagram: createCityLoopDiagram("red", [
    stop.JOLIMONT,
    stop.WEST_RICHMOND,
    stop.NORTH_RICHMOND,
    stop.COLLINGWOOD,
    stop.VICTORIA_PARK,
    stop.CLIFTON_HILL,
    stop.WESTGARTH,
    stop.DENNIS,
    stop.FAIRFIELD,
    stop.ALPHINGTON,
    stop.DAREBIN,
    stop.IVANHOE,
    stop.EAGLEMONT,
    stop.HEIDELBERG,
    stop.ROSANNA,
    stop.MACLEOD,
    stop.WATSONIA,
    stop.GREENSBOROUGH,
    stop.MONTMORENCY,
    stop.ELTHAM,
    stop.DIAMOND_CREEK,
    stop.WATTLE_GLEN,
    stop.HURSTBRIDGE,
  ]),
};

export const LILYDALE: LineConfig = {
  id: line.LILYDALE,
  name: "Lilydale",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "lilydale",
  color: "blue",
  diagram: createCityLoopDiagram("blue", [
    stop.RICHMOND,
    stop.EAST_RICHMOND,
    stop.BURNLEY,
    stop.HAWTHORN,
    stop.GLENFERRIE,
    stop.AUBURN,
    stop.CAMBERWELL,
    stop.EAST_CAMBERWELL,
    stop.CANTERBURY,
    stop.CHATHAM,
    stop.UNION,
    stop.BOX_HILL,
    stop.LABURNUM,
    stop.BLACKBURN,
    stop.NUNAWADING,
    stop.MITCHAM,
    stop.HEATHERDALE,
    stop.RINGWOOD,
    stop.RINGWOOD_EAST,
    stop.CROYDON,
    stop.MOOROOLBARK,
    stop.LILYDALE,
  ]),
};

export const MERNDA: LineConfig = {
  id: line.MERNDA,
  name: "Mernda",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "mernda",
  color: "red",
  diagram: createCityLoopDiagram("red", [
    stop.JOLIMONT,
    stop.WEST_RICHMOND,
    stop.NORTH_RICHMOND,
    stop.COLLINGWOOD,
    stop.VICTORIA_PARK,
    stop.CLIFTON_HILL,
    stop.RUSHALL,
    stop.MERRI,
    stop.NORTHCOTE,
    stop.CROXTON,
    stop.THORNBURY,
    stop.BELL,
    stop.PRESTON,
    stop.REGENT,
    stop.RESERVOIR,
    stop.RUTHVEN,
    stop.KEON_PARK,
    stop.THOMASTOWN,
    stop.LALOR,
    stop.EPPING,
    stop.SOUTH_MORANG,
    stop.MIDDLE_GORGE,
    stop.HAWKSTOWE,
    stop.MERNDA,
  ]),
};

export const PAKENHAM: LineConfig = {
  id: line.PAKENHAM,
  name: "Pakenham",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "pakenham",
  color: "cyan",
  diagram: createLinearDiagram("cyan", [
    stop.TOWN_HALL,
    stop.ANZAC,
    { stopId: stop.HAWKSBURN, type: "always-express" },
    { stopId: stop.TOORAK, type: "always-express" },
    { stopId: stop.ARMADALE, type: "always-express" },
    stop.MALVERN,
    stop.CAULFIELD,
    stop.CARNEGIE,
    stop.MURRUMBEENA,
    stop.HUGHESDALE,
    stop.OAKLEIGH,
    stop.HUNTINGDALE,
    stop.CLAYTON,
    stop.WESTALL,
    stop.SPRINGVALE,
    stop.SANDOWN_PARK,
    stop.NOBLE_PARK,
    stop.YARRAMAN,
    stop.DANDENONG,
    stop.HALLAM,
    stop.NARRE_WARREN,
    stop.BERWICK,
    stop.BEACONSFIELD,
    stop.OFFICER,
    stop.CARDINIA_ROAD,
    stop.PAKENHAM,
    stop.EAST_PAKENHAM,
  ]),
};

export const SANDRINGHAM: LineConfig = {
  id: line.SANDRINGHAM,
  name: "Sandringham",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "sandringham",
  color: "pink",
  diagram: createLinearDiagram("pink", [
    stop.FLINDERS_STREET,
    stop.RICHMOND,
    stop.SOUTH_YARRA,
    stop.PRAHRAN,
    stop.WINDSOR,
    stop.BALACLAVA,
    stop.RIPPONLEA,
    stop.ELSTERNWICK,
    stop.GARDENVALE,
    stop.NORTH_BRIGHTON,
    stop.MIDDLE_BRIGHTON,
    stop.BRIGHTON_BEACH,
    stop.HAMPTON,
    stop.SANDRINGHAM,
  ]),
};

export const SEYMOUR: LineConfig = {
  id: line.SEYMOUR,
  name: "Seymour",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "seymour",
  color: "purple",
  diagram: {
    entries: [
      {
        name: null,
        color: "purple",
        shape: {
          type: "branch",
          commonStops: formalizeDiagramStops([
            stop.SOUTHERN_CROSS,
            stop.NORTH_MELBOURNE,
            stop.ESSENDON,
            stop.BROADMEADOWS,
            stop.CRAIGIEBURN,
            stop.DONNYBROOK,
            stop.WALLAN,
            stop.HEATHCOTE_JUNCTION,
            stop.WANDONG,
            stop.KILMORE_EAST,
            stop.BROADFORD,
            stop.TALLAROOK,
            stop.SEYMOUR,
          ]),
          branchAStops: formalizeDiagramStops([
            stop.AVENEL,
            stop.EUROA,
            stop.VIOLET_TOWN,
            stop.BENALLA,
            stop.WANGARATTA,
            stop.SPRINGHURST,
            stop.CHILTERN,
            stop.WODONGA,
            stop.ALBURY,
          ]),
          branchBStops: formalizeDiagramStops([
            stop.NAGAMBIE,
            stop.MURCHISON_EAST,
            stop.MOOROOPNA,
            stop.SHEPPARTON,
          ]),
        },
      },
    ],
  },
};

export const STONY_POINT: LineConfig = {
  id: line.STONY_POINT,
  name: "Stony Point",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "stonypoint",
  color: "green",
  diagram: createLinearDiagram("green", [
    stop.FRANKSTON,
    stop.LEAWARRA,
    stop.BAXTER,
    stop.SOMERVILLE,
    stop.TYABB,
    stop.HASTINGS,
    stop.BITTERN,
    stop.MORRADOO,
    stop.CRIB_POINT,
    stop.STONY_POINT,
  ]),
};

export const SUNBURY: LineConfig = {
  id: line.SUNBURY,
  name: "Sunbury",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "sunbury",
  color: "cyan",
  diagram: createLinearDiagram("cyan", [
    stop.TOWN_HALL,
    stop.STATE_LIBRARY,
    stop.PARKVILLE,
    stop.ARDEN,
    stop.FOOTSCRAY,
    stop.MIDDLE_FOOTSCRAY,
    stop.WEST_FOOTSCRAY,
    stop.TOTTENHAM,
    stop.SUNSHINE,
    stop.ALBION,
    stop.GINIFER,
    stop.ST_ALBANS,
    stop.KEILOR_PLAINS,
    stop.WATERGARDENS,
    stop.DIGGERS_REST,
    stop.SUNBURY,
  ]),
};

export const UPFIELD: LineConfig = {
  id: line.UPFIELD,
  name: "Upfield",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "upfield",
  color: "yellow",
  diagram: createCityLoopDiagram("yellow", [
    stop.NORTH_MELBOURNE,
    stop.MACAULAY,
    stop.FLEMINGTON_BRIDGE,
    stop.ROYAL_PARK,
    stop.JEWELL,
    stop.BRUNSWICK,
    stop.ANSTEY,
    stop.MORELAND,
    stop.COBURG,
    stop.BATMAN,
    stop.MERLYNSTON,
    stop.FAWKNER,
    stop.GOWRIE,
    stop.UPFIELD,
  ]),
};

export const WERRIBEE: LineConfig = {
  id: line.WERRIBEE,
  name: "Werribee",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "werribee",
  color: "pink",
  diagram: createLinearDiagram("pink", [
    stop.FLINDERS_STREET,
    stop.SOUTHERN_CROSS,
    stop.NORTH_MELBOURNE,
    stop.SOUTH_KENSINGTON,
    stop.FOOTSCRAY,
    stop.SEDDON,
    stop.YARRAVILLE,
    stop.SPOTSWOOD,
    stop.NEWPORT,
    stop.SEAHOLME,
    stop.ALTONA,
    stop.WESTONA,
    stop.LAVERTON,
    stop.AIRCRAFT,
    stop.WILLIAMS_LANDING,
    stop.HOPPERS_CROSSING,
    stop.WERRIBEE,
  ]),
};

export const WILLIAMSTOWN: LineConfig = {
  id: line.WILLIAMSTOWN,
  name: "Williamstown",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "williamstown",
  color: "pink",
  diagram: createLinearDiagram("pink", [
    stop.FLINDERS_STREET,
    stop.SOUTHERN_CROSS,
    stop.NORTH_MELBOURNE,
    stop.SOUTH_KENSINGTON,
    stop.FOOTSCRAY,
    stop.SEDDON,
    stop.YARRAVILLE,
    stop.SPOTSWOOD,
    stop.NEWPORT,
    stop.NORTH_WILLIAMSTOWN,
    stop.WILLIAMSTOWN_BEACH,
    stop.WILLIAMSTOWN,
  ]),
};
