export const AIRCRAFT = 1; // Aircraft
export const ALAMEIN = 2; // Alamein
export const ALBION = 3; // Albion
export const ALBURY = 4; // Albury
export const ALPHINGTON = 5; // Alphington
export const ALTONA = 6; // Altona
export const ANSTEY = 7; // Anstey
export const ARARAT = 8; // Ararat
export const ARDEER = 9; // Ardeer
export const ARMADALE = 10; // Armadale
export const ASCOT_VALE = 11; // Ascot Vale
export const ASHBURTON = 12; // Ashburton
export const ASPENDALE = 13; // Aspendale
export const AUBURN = 14; // Auburn
export const AVENEL = 15; // Avenel
export const BACCHUS_MARSH = 16; // Bacchus Marsh
export const BAIRNSDALE = 17; // Bairnsdale
export const BALACLAVA = 18; // Balaclava
export const BALLAN = 19; // Ballan
export const BALLARAT = 20; // Ballarat
export const BATMAN = 21; // Batman
export const BAXTER = 22; // Baxter
export const BAYSWATER = 23; // Bayswater
export const BEACONSFIELD = 24; // Beaconsfield
export const BEAUFORT = 25; // Beaufort
export const BELGRAVE = 26; // Belgrave
export const BELL = 27; // Bell
export const BENALLA = 28; // Benalla
export const BENDIGO = 29; // Bendigo
export const BENTLEIGH = 30; // Bentleigh
export const BERWICK = 31; // Berwick
export const BIRREGURRA = 32; // Birregurra
export const BITTERN = 33; // Bittern
export const BLACKBURN = 34; // Blackburn
export const BONBEACH = 35; // Bonbeach
export const BORONIA = 36; // Boronia
export const BOX_HILL = 37; // Box Hill
export const BRIGHTON_BEACH = 38; // Brighton Beach
export const BROADFORD = 39; // Broadford
export const BROADMEADOWS = 40; // Broadmeadows
export const BRUNSWICK = 41; // Brunswick
export const BUNYIP = 42; // Bunyip
export const BURNLEY = 43; // Burnley
export const BURWOOD = 44; // Burwood
export const CAMBERWELL = 45; // Camberwell
export const CAMPERDOWN = 46; // Camperdown
export const CANTERBURY = 47; // Canterbury
export const CARDINIA_ROAD = 48; // Cardinia Road
export const CARNEGIE = 49; // Carnegie
export const CAROLINE_SPRINGS = 50; // Caroline Springs
export const CARRUM = 51; // Carrum
export const CASTLEMAINE = 52; // Castlemaine
export const CAULFIELD = 53; // Caulfield
export const CHATHAM = 54; // Chatham
export const CHELSEA = 55; // Chelsea
export const CHELTENHAM = 56; // Cheltenham
export const CHILTERN = 57; // Chiltern
export const CLARKEFIELD = 58; // Clarkefield
export const CLAYTON = 59; // Clayton
export const CLIFTON_HILL = 60; // Clifton Hill
export const CLUNES = 61; // Clunes
export const COBBLEBANK = 62; // Cobblebank
export const COBURG = 63; // Coburg
export const COLAC = 64; // Colac
export const COLLINGWOOD = 65; // Collingwood
export const COOLAROO = 66; // Coolaroo
export const CORIO = 67; // Corio
export const CRAIGIEBURN = 68; // Craigieburn
export const CRANBOURNE = 69; // Cranbourne
export const CRESWICK = 70; // Creswick
export const CRIB_POINT = 71; // Crib Point
export const CROXTON = 72; // Croxton
export const CROYDON = 73; // Croydon
export const DANDENONG = 74; // Dandenong
export const DAREBIN = 75; // Darebin
export const DARLING = 76; // Darling
export const DEER_PARK = 77; // Deer Park
export const DENNIS = 78; // Dennis
export const DIAMOND_CREEK = 79; // Diamond Creek
export const DIGGERS_REST = 80; // Diggers Rest
export const DINGEE = 81; // Dingee
export const DONNYBROOK = 82; // Donnybrook
export const DROUIN = 83; // Drouin
export const EAGLEHAWK = 84; // Eaglehawk
export const EAGLEMONT = 85; // Eaglemont
export const EAST_CAMBERWELL = 86; // East Camberwell
export const EAST_MALVERN = 87; // East Malvern
export const EAST_RICHMOND = 88; // East Richmond
export const ECHUCA = 89; // Echuca
export const EDITHVALE = 90; // Edithvale
export const ELMORE = 91; // Elmore
export const ELSTERNWICK = 92; // Elsternwick
export const ELTHAM = 93; // Eltham
export const EPPING = 94; // Epping
export const EPSOM = 95; // Epsom
export const ESSENDON = 96; // Essendon
export const EUROA = 97; // Euroa
export const FAIRFIELD = 98; // Fairfield
export const FAWKNER = 99; // Fawkner
export const FERNTREE_GULLY = 100; // Ferntree Gully
export const FLAGSTAFF = 101; // Flagstaff
export const FLEMINGTON_BRIDGE = 102; // Flemington Bridge
export const FLEMINGTON_RACECOURSE = 103; // Flemington Racecourse
export const FLINDERS_STREET = 104; // Flinders Street
export const FOOTSCRAY = 105; // Footscray
export const FRANKSTON = 106; // Frankston
export const GARDENVALE = 107; // Gardenvale
export const GARDINER = 108; // Gardiner
export const GARFIELD = 109; // Garfield
export const GEELONG = 110; // Geelong
export const GINIFER = 111; // Ginifer
export const GISBORNE = 112; // Gisborne
export const GLEN_IRIS = 113; // Glen Iris
export const GLEN_WAVERLEY = 114; // Glen Waverley
export const GLENBERVIE = 115; // Glenbervie
export const GLENFERRIE = 116; // Glenferrie
export const GLEN_HUNTLY = 117; // Glen Huntly
export const GLENROY = 118; // Glenroy
export const GOORNONG = 119; // Goornong
export const GOWRIE = 120; // Gowrie
export const GREENSBOROUGH = 121; // Greensborough
export const HALLAM = 122; // Hallam
export const HAMPTON = 123; // Hampton
export const HARTWELL = 124; // Hartwell
export const HASTINGS = 125; // Hastings
export const HAWKSBURN = 126; // Hawksburn
export const HAWKSTOWE = 127; // Hawkstowe
export const HAWTHORN = 128; // Hawthorn
export const HEATHCOTE_JUNCTION = 129; // Heathcote Junction
export const HEATHERDALE = 130; // Heatherdale
export const HEATHMONT = 131; // Heathmont
export const HEIDELBERG = 132; // Heidelberg
export const HEYINGTON = 133; // Heyington
export const HIGHETT = 134; // Highett
export const HOLMESGLEN = 135; // Holmesglen
export const HOPPERS_CROSSING = 136; // Hoppers Crossing
export const HUGHESDALE = 137; // Hughesdale
export const HUNTINGDALE = 138; // Huntingdale
export const HURSTBRIDGE = 139; // Hurstbridge
export const IVANHOE = 140; // Ivanhoe
export const JACANA = 141; // Jacana
export const JEWELL = 142; // Jewell
export const JOLIMONT = 143; // Jolimont
export const JORDANVILLE = 144; // Jordanville
export const KANANOOK = 145; // Kananook
export const KANGAROO_FLAT = 146; // Kangaroo Flat
export const KEILOR_PLAINS = 147; // Keilor Plains
export const KENSINGTON = 148; // Kensington
export const KEON_PARK = 149; // Keon Park
export const KERANG = 150; // Kerang
export const KILMORE_EAST = 151; // Kilmore East
export const KOOYONG = 152; // Kooyong
export const KYNETON = 153; // Kyneton
export const LABURNUM = 154; // Laburnum
export const LALOR = 155; // Lalor
export const LARA = 156; // Lara
export const LAVERTON = 157; // Laverton
export const LEAWARRA = 158; // Leawarra
export const LILYDALE = 159; // Lilydale
export const LITTLE_RIVER = 160; // Little River
export const LONGWARRY = 161; // Longwarry
export const LYNBROOK = 162; // Lynbrook
export const MACAULAY = 163; // Macaulay
export const MACEDON = 164; // Macedon
export const MACLEOD = 165; // Macleod
export const MALMSBURY = 166; // Malmsbury
export const MALVERN = 167; // Malvern
export const MARSHALL = 168; // Marshall
export const MARYBOROUGH = 169; // Maryborough
export const MCKINNON = 170; // McKinnon
export const MELBOURNE_CENTRAL = 171; // Melbourne Central
export const MELTON = 172; // Melton
export const MENTONE = 173; // Mentone
export const MERINDA_PARK = 174; // Merinda Park
export const MERLYNSTON = 175; // Merlynston
export const MERNDA = 176; // Mernda
export const MERRI = 177; // Merri
export const MIDDLE_BRIGHTON = 178; // Middle Brighton
export const MIDDLE_FOOTSCRAY = 179; // Middle Footscray
export const MIDDLE_GORGE = 180; // Middle Gorge
export const MITCHAM = 181; // Mitcham
export const MOE = 182; // Moe
// [REMOVED] export const MONT_ALBERT = 183; // Mont Albert
export const MONTMORENCY = 184; // Montmorency
export const MOONEE_PONDS = 185; // Moonee Ponds
export const MOORABBIN = 186; // Moorabbin
export const MOOROOLBARK = 187; // Mooroolbark
export const MOOROOPNA = 188; // Mooroopna
export const MORDIALLOC = 189; // Mordialloc
export const MORELAND = 190; // Moreland
export const MORRADOO = 191; // Morradoo
export const MORWELL = 192; // Morwell
export const MOUNT_WAVERLEY = 193; // Mount Waverley
export const MURCHISON_EAST = 194; // Murchison East
export const MURRUMBEENA = 195; // Murrumbeena
export const NAGAMBIE = 196; // Nagambie
export const NAR_NAR_GOON = 197; // Nar Nar Goon
export const NARRE_WARREN = 198; // Narre Warren
export const NEWMARKET = 199; // Newmarket
export const NEWPORT = 200; // Newport
export const NOBLE_PARK = 201; // Noble Park
export const NORTH_BRIGHTON = 202; // North Brighton
export const NORTH_GEELONG = 203; // North Geelong
export const NORTH_MELBOURNE = 204; // North Melbourne
export const NORTH_RICHMOND = 205; // North Richmond
export const NORTH_SHORE = 206; // North Shore
export const NORTH_WILLIAMSTOWN = 207; // North Williamstown
export const NORTHCOTE = 208; // Northcote
export const NUNAWADING = 209; // Nunawading
export const OAK_PARK = 210; // Oak Park
export const OAKLEIGH = 211; // Oakleigh
export const OFFICER = 212; // Officer
export const ORMOND = 213; // Ormond
export const PAKENHAM = 214; // Pakenham
export const PARKDALE = 215; // Parkdale
export const PARLIAMENT = 216; // Parliament
export const PASCOE_VALE = 217; // Pascoe Vale
export const PATTERSON = 218; // Patterson
export const PRAHRAN = 219; // Prahran
export const PRESTON = 220; // Preston
export const PYRAMID = 221; // Pyramid
export const REGENT = 222; // Regent
export const RESERVOIR = 223; // Reservoir
export const RICHMOND = 224; // Richmond
export const RIDDELLS_CREEK = 225; // Riddells Creek
export const RINGWOOD = 226; // Ringwood
export const RINGWOOD_EAST = 227; // Ringwood East
export const RIPPONLEA = 228; // Ripponlea
export const RIVERSDALE = 229; // Riversdale
export const ROCHESTER = 230; // Rochester
export const ROCKBANK = 231; // Rockbank
export const ROSANNA = 232; // Rosanna
export const ROSEDALE = 233; // Rosedale
export const ROXBURGH_PARK = 234; // Roxburgh Park
export const ROYAL_PARK = 235; // Royal Park
export const RUSHALL = 236; // Rushall
export const RUTHVEN = 237; // Ruthven
export const SALE = 238; // Sale
export const SANDOWN_PARK = 239; // Sandown Park
export const SANDRINGHAM = 240; // Sandringham
export const SEAFORD = 241; // Seaford
export const SEAHOLME = 242; // Seaholme
export const SEDDON = 243; // Seddon
export const SEYMOUR = 244; // Seymour
export const SHEPPARTON = 245; // Shepparton
export const SHERWOOD_PARK = 246; // Sherwood Park
export const SHOWGROUNDS = 247; // Showgrounds
export const SOMERVILLE = 248; // Somerville
export const SOUTH_GEELONG = 249; // South Geelong
export const SOUTH_KENSINGTON = 250; // South Kensington
export const SOUTH_MORANG = 251; // South Morang
export const SOUTH_YARRA = 252; // South Yarra
export const SOUTHERN_CROSS = 253; // Southern Cross
export const SOUTHLAND = 254; // Southland
export const SPOTSWOOD = 255; // Spotswood
export const SPRINGHURST = 256; // Springhurst
export const SPRINGVALE = 257; // Springvale
export const ST_ALBANS = 258; // St Albans
export const STONY_POINT = 259; // Stony Point
export const STRATFORD = 260; // Stratford
export const STRATHMORE = 261; // Strathmore
export const SUNBURY = 262; // Sunbury
export const SUNSHINE = 263; // Sunshine
// [REMOVED] export const SURREY_HILLS = 264; // Surrey Hills
export const SWAN_HILL = 265; // Swan Hill
export const SYNDAL = 266; // Syndal
export const TALBOT = 267; // Talbot
export const TALLAROOK = 268; // Tallarook
export const TARNEIT = 269; // Tarneit
export const TECOMA = 270; // Tecoma
export const TERANG = 271; // Terang
export const THOMASTOWN = 272; // Thomastown
export const THORNBURY = 273; // Thornbury
export const TOORAK = 274; // Toorak
export const TOORONGA = 275; // Tooronga
export const TOTTENHAM = 276; // Tottenham
export const TRAFALGAR = 277; // Trafalgar
export const TRARALGON = 278; // Traralgon
export const TYABB = 279; // Tyabb
export const TYNONG = 280; // Tynong
export const UPFIELD = 281; // Upfield
export const UPPER_FERNTREE_GULLY = 282; // Upper Ferntree Gully
export const UPWEY = 283; // Upwey
export const VICTORIA_PARK = 284; // Victoria Park
export const VIOLET_TOWN = 285; // Violet Town
export const WALLAN = 286; // Wallan
export const WANDONG = 287; // Wandong
export const WANGARATTA = 288; // Wangaratta
export const WARRAGUL = 289; // Warragul
export const WARRNAMBOOL = 290; // Warrnambool
export const WATERGARDENS = 291; // Watergardens
export const WATSONIA = 292; // Watsonia
export const WATTLE_GLEN = 293; // Wattle Glen
export const WAURN_PONDS = 294; // Waurn Ponds
export const WENDOUREE = 295; // Wendouree
export const WERRIBEE = 296; // Werribee
export const WEST_FOOTSCRAY = 297; // West Footscray
export const WEST_RICHMOND = 298; // West Richmond
export const WESTALL = 299; // Westall
export const WESTGARTH = 300; // Westgarth
export const WESTONA = 301; // Westona
export const WILLIAMS_LANDING = 302; // Williams Landing
export const WILLIAMSTOWN = 303; // Williamstown
export const WILLIAMSTOWN_BEACH = 304; // Williamstown Beach
export const WILLISON = 305; // Willison
export const WINCHELSEA = 306; // Winchelsea
export const WINDSOR = 307; // Windsor
export const WODONGA = 308; // Wodonga
export const WOODEND = 309; // Woodend
export const WYNDHAM_VALE = 310; // Wyndham Vale
export const YARRAGON = 311; // Yarragon
export const YARRAMAN = 312; // Yarraman
export const YARRAVILLE = 313; // Yarraville
export const HUNTLY = 314; // Huntly
export const RAYWOOD = 315; // Raywood
export const UNION = 316; // Union
export const EAST_PAKENHAM = 317; // East Pakenham
export const ANZAC = 318; // Anzac
export const TOWN_HALL = 319; // Town Hall
export const STATE_LIBRARY = 320; // State Library
export const PARKVILLE = 321; // Parkville
export const ARDEN = 322; // Arden
