export const SANDRINGHAM = 1; // Sandringham
export const FRANKSTON = 2; // Frankston
export const STONY_POINT = 3; // Stony Point
export const CRANBOURNE = 4; // Cranbourne
export const PAKENHAM = 5; // Pakenham
export const GIPPSLAND = 6; // Gippsland
export const GLEN_WAVERLEY = 7; // Glen Waverley
export const ALAMEIN = 8; // Alamein
export const BELGRAVE = 9; // Belgrave
export const LILYDALE = 10; // Lilydale
export const HURSTBRIDGE = 11; // Hurstbridge
export const MERNDA = 12; // Mernda
export const UPFIELD = 13; // Upfield
export const CRAIGIEBURN = 14; // Craigieburn
export const SEYMOUR = 15; // Seymour
export const FLEMINGTON_RACECOURSE = 16; // Flemington Racecourse
export const SUNBURY = 17; // Sunbury
export const BENDIGO = 18; // Bendigo
export const BALLARAT = 19; // Ballarat
export const GEELONG = 20; // Geelong
export const WERRIBEE = 21; // Werribee
export const WILLIAMSTOWN = 22; // Williamstown
export const ALBURY = 23; // Albury
export const ARARAT = 24; // Ararat
export const BAIRNSDALE = 25; // Bairnsdale
export const ECHUCA = 26; // Echuca
export const MARYBOROUGH = 27; // Maryborough
export const SHEPPARTON = 28; // Shepparton
export const SWAN_HILL = 29; // Swan Hill
export const WARRNAMBOOL = 30; // Warrnambool
