import { type LineConfig } from "corequery";
import * as line from "./line-ids.js";
import * as route from "./route-ids.js";
import * as stop from "../stops/stop-ids.js";

export const SANDRINGHAM: LineConfig = {
  id: line.SANDRINGHAM,
  name: "Sandringham",
  code: null,
  tags: [],
  urlPath: "sandringham",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.SANDRINGHAM, type: "regular" },
        { stopId: stop.HAMPTON, type: "regular" },
        { stopId: stop.BRIGHTON_BEACH, type: "regular" },
        { stopId: stop.MIDDLE_BRIGHTON, type: "regular" },
        { stopId: stop.NORTH_BRIGHTON, type: "regular" },
        { stopId: stop.GARDENVALE, type: "regular" },
        { stopId: stop.ELSTERNWICK, type: "regular" },
        { stopId: stop.RIPPONLEA, type: "regular" },
        { stopId: stop.BALACLAVA, type: "regular" },
        { stopId: stop.WINDSOR, type: "regular" },
        { stopId: stop.PRAHRAN, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.PRAHRAN, type: "regular" },
        { stopId: stop.WINDSOR, type: "regular" },
        { stopId: stop.BALACLAVA, type: "regular" },
        { stopId: stop.RIPPONLEA, type: "regular" },
        { stopId: stop.ELSTERNWICK, type: "regular" },
        { stopId: stop.GARDENVALE, type: "regular" },
        { stopId: stop.NORTH_BRIGHTON, type: "regular" },
        { stopId: stop.MIDDLE_BRIGHTON, type: "regular" },
        { stopId: stop.BRIGHTON_BEACH, type: "regular" },
        { stopId: stop.HAMPTON, type: "regular" },
        { stopId: stop.SANDRINGHAM, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const FRANKSTON: LineConfig = {
  id: line.FRANKSTON,
  name: "Frankston",
  code: null,
  tags: [],
  urlPath: "frankston",
  routes: [
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.HAWKSBURN, type: "regular" },
        { stopId: stop.TOORAK, type: "regular" },
        { stopId: stop.ARMADALE, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.GLEN_HUNTLY, type: "regular" },
        { stopId: stop.ORMOND, type: "regular" },
        { stopId: stop.MCKINNON, type: "regular" },
        { stopId: stop.BENTLEIGH, type: "regular" },
        { stopId: stop.PATTERSON, type: "regular" },
        { stopId: stop.MOORABBIN, type: "regular" },
        { stopId: stop.HIGHETT, type: "regular" },
        { stopId: stop.SOUTHLAND, type: "regular" },
        { stopId: stop.CHELTENHAM, type: "regular" },
        { stopId: stop.MENTONE, type: "regular" },
        { stopId: stop.PARKDALE, type: "regular" },
        { stopId: stop.MORDIALLOC, type: "regular" },
        { stopId: stop.ASPENDALE, type: "regular" },
        { stopId: stop.EDITHVALE, type: "regular" },
        { stopId: stop.CHELSEA, type: "regular" },
        { stopId: stop.BONBEACH, type: "regular" },
        { stopId: stop.CARRUM, type: "regular" },
        { stopId: stop.SEAFORD, type: "regular" },
        { stopId: stop.KANANOOK, type: "regular" },
        { stopId: stop.FRANKSTON, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FRANKSTON, type: "regular" },
        { stopId: stop.KANANOOK, type: "regular" },
        { stopId: stop.SEAFORD, type: "regular" },
        { stopId: stop.CARRUM, type: "regular" },
        { stopId: stop.BONBEACH, type: "regular" },
        { stopId: stop.CHELSEA, type: "regular" },
        { stopId: stop.EDITHVALE, type: "regular" },
        { stopId: stop.ASPENDALE, type: "regular" },
        { stopId: stop.MORDIALLOC, type: "regular" },
        { stopId: stop.PARKDALE, type: "regular" },
        { stopId: stop.MENTONE, type: "regular" },
        { stopId: stop.CHELTENHAM, type: "regular" },
        { stopId: stop.SOUTHLAND, type: "regular" },
        { stopId: stop.HIGHETT, type: "regular" },
        { stopId: stop.MOORABBIN, type: "regular" },
        { stopId: stop.PATTERSON, type: "regular" },
        { stopId: stop.BENTLEIGH, type: "regular" },
        { stopId: stop.MCKINNON, type: "regular" },
        { stopId: stop.ORMOND, type: "regular" },
        { stopId: stop.GLEN_HUNTLY, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.ARMADALE, type: "regular" },
        { stopId: stop.TOORAK, type: "regular" },
        { stopId: stop.HAWKSBURN, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const STONY_POINT: LineConfig = {
  id: line.STONY_POINT,
  name: "Stony Point",
  code: null,
  tags: [],
  urlPath: "stonypoint",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.STONY_POINT, type: "regular" },
        { stopId: stop.CRIB_POINT, type: "regular" },
        { stopId: stop.MORRADOO, type: "regular" },
        { stopId: stop.BITTERN, type: "regular" },
        { stopId: stop.HASTINGS, type: "regular" },
        { stopId: stop.TYABB, type: "regular" },
        { stopId: stop.SOMERVILLE, type: "regular" },
        { stopId: stop.BAXTER, type: "regular" },
        { stopId: stop.LEAWARRA, type: "regular" },
        { stopId: stop.FRANKSTON, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.FRANKSTON, type: "regular" },
        { stopId: stop.LEAWARRA, type: "regular" },
        { stopId: stop.BAXTER, type: "regular" },
        { stopId: stop.SOMERVILLE, type: "regular" },
        { stopId: stop.TYABB, type: "regular" },
        { stopId: stop.HASTINGS, type: "regular" },
        { stopId: stop.BITTERN, type: "regular" },
        { stopId: stop.MORRADOO, type: "regular" },
        { stopId: stop.CRIB_POINT, type: "regular" },
        { stopId: stop.STONY_POINT, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const CRANBOURNE: LineConfig = {
  id: line.CRANBOURNE,
  name: "Cranbourne",
  code: null,
  tags: [],
  urlPath: "cranbourne",
  routes: [
    {
      id: route.DOWN_VIA_METRO_TUNNEL,
      name: "Down via Metro Tunnel",
      tags: [],
      stops: [
        { stopId: stop.TOWN_HALL, type: "regular" },
        { stopId: stop.ANZAC, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.LYNBROOK, type: "regular" },
        { stopId: stop.MERINDA_PARK, type: "regular" },
        { stopId: stop.CRANBOURNE, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_METRO_TUNNEL,
      name: "Up via Metro Tunnel",
      tags: [],
      stops: [
        { stopId: stop.CRANBOURNE, type: "regular" },
        { stopId: stop.MERINDA_PARK, type: "regular" },
        { stopId: stop.LYNBROOK, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.ANZAC, type: "regular" },
        { stopId: stop.TOWN_HALL, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.CRANBOURNE, type: "regular" },
        { stopId: stop.MERINDA_PARK, type: "regular" },
        { stopId: stop.LYNBROOK, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.LYNBROOK, type: "regular" },
        { stopId: stop.MERINDA_PARK, type: "regular" },
        { stopId: stop.CRANBOURNE, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const PAKENHAM: LineConfig = {
  id: line.PAKENHAM,
  name: "Pakenham",
  code: null,
  tags: [],
  urlPath: "pakenham",
  routes: [
    {
      id: route.DOWN_VIA_METRO_TUNNEL,
      name: "Down via Metro Tunnel",
      tags: [],
      stops: [
        { stopId: stop.TOWN_HALL, type: "regular" },
        { stopId: stop.ANZAC, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.HALLAM, type: "regular" },
        { stopId: stop.NARRE_WARREN, type: "regular" },
        { stopId: stop.BERWICK, type: "regular" },
        { stopId: stop.BEACONSFIELD, type: "regular" },
        { stopId: stop.OFFICER, type: "regular" },
        { stopId: stop.CARDINIA_ROAD, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.EAST_PAKENHAM, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_METRO_TUNNEL,
      name: "Up via Metro Tunnel",
      tags: [],
      stops: [
        { stopId: stop.EAST_PAKENHAM, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.CARDINIA_ROAD, type: "regular" },
        { stopId: stop.OFFICER, type: "regular" },
        { stopId: stop.BEACONSFIELD, type: "regular" },
        { stopId: stop.BERWICK, type: "regular" },
        { stopId: stop.NARRE_WARREN, type: "regular" },
        { stopId: stop.HALLAM, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.ANZAC, type: "regular" },
        { stopId: stop.TOWN_HALL, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.HALLAM, type: "regular" },
        { stopId: stop.NARRE_WARREN, type: "regular" },
        { stopId: stop.BERWICK, type: "regular" },
        { stopId: stop.BEACONSFIELD, type: "regular" },
        { stopId: stop.OFFICER, type: "regular" },
        { stopId: stop.CARDINIA_ROAD, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.EAST_PAKENHAM, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.EAST_PAKENHAM, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.CARDINIA_ROAD, type: "regular" },
        { stopId: stop.OFFICER, type: "regular" },
        { stopId: stop.BEACONSFIELD, type: "regular" },
        { stopId: stop.BERWICK, type: "regular" },
        { stopId: stop.NARRE_WARREN, type: "regular" },
        { stopId: stop.HALLAM, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.YARRAMAN, type: "regular" },
        { stopId: stop.NOBLE_PARK, type: "regular" },
        { stopId: stop.SANDOWN_PARK, type: "regular" },
        { stopId: stop.SPRINGVALE, type: "regular" },
        { stopId: stop.WESTALL, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.HUNTINGDALE, type: "regular" },
        { stopId: stop.OAKLEIGH, type: "regular" },
        { stopId: stop.HUGHESDALE, type: "regular" },
        { stopId: stop.MURRUMBEENA, type: "regular" },
        { stopId: stop.CARNEGIE, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.MALVERN, type: "regular" },
        { stopId: stop.SOUTH_YARRA, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const GIPPSLAND: LineConfig = {
  id: line.GIPPSLAND,
  name: "Gippsland",
  code: null,
  tags: [],
  urlPath: "gippsland",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.TRARALGON, type: "regular" },
        { stopId: stop.MORWELL, type: "regular" },
        { stopId: stop.MOE, type: "regular" },
        { stopId: stop.TRAFALGAR, type: "regular" },
        { stopId: stop.YARRAGON, type: "regular" },
        { stopId: stop.WARRAGUL, type: "regular" },
        { stopId: stop.DROUIN, type: "regular" },
        { stopId: stop.LONGWARRY, type: "regular" },
        { stopId: stop.BUNYIP, type: "regular" },
        { stopId: stop.GARFIELD, type: "regular" },
        { stopId: stop.TYNONG, type: "regular" },
        { stopId: stop.NAR_NAR_GOON, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.BERWICK, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.BERWICK, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.NAR_NAR_GOON, type: "regular" },
        { stopId: stop.TYNONG, type: "regular" },
        { stopId: stop.GARFIELD, type: "regular" },
        { stopId: stop.BUNYIP, type: "regular" },
        { stopId: stop.LONGWARRY, type: "regular" },
        { stopId: stop.DROUIN, type: "regular" },
        { stopId: stop.WARRAGUL, type: "regular" },
        { stopId: stop.YARRAGON, type: "regular" },
        { stopId: stop.TRAFALGAR, type: "regular" },
        { stopId: stop.MOE, type: "regular" },
        { stopId: stop.MORWELL, type: "regular" },
        { stopId: stop.TRARALGON, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const GLEN_WAVERLEY: LineConfig = {
  id: line.GLEN_WAVERLEY,
  name: "Glen Waverley",
  code: null,
  tags: [],
  urlPath: "glenwaverley",
  routes: [
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.GLEN_WAVERLEY, type: "regular" },
        { stopId: stop.SYNDAL, type: "regular" },
        { stopId: stop.MOUNT_WAVERLEY, type: "regular" },
        { stopId: stop.JORDANVILLE, type: "regular" },
        { stopId: stop.HOLMESGLEN, type: "regular" },
        { stopId: stop.EAST_MALVERN, type: "regular" },
        { stopId: stop.DARLING, type: "regular" },
        { stopId: stop.GLEN_IRIS, type: "regular" },
        { stopId: stop.GARDINER, type: "regular" },
        { stopId: stop.TOORONGA, type: "regular" },
        { stopId: stop.KOOYONG, type: "regular" },
        { stopId: stop.HEYINGTON, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.HEYINGTON, type: "regular" },
        { stopId: stop.KOOYONG, type: "regular" },
        { stopId: stop.TOORONGA, type: "regular" },
        { stopId: stop.GARDINER, type: "regular" },
        { stopId: stop.GLEN_IRIS, type: "regular" },
        { stopId: stop.DARLING, type: "regular" },
        { stopId: stop.EAST_MALVERN, type: "regular" },
        { stopId: stop.HOLMESGLEN, type: "regular" },
        { stopId: stop.JORDANVILLE, type: "regular" },
        { stopId: stop.MOUNT_WAVERLEY, type: "regular" },
        { stopId: stop.SYNDAL, type: "regular" },
        { stopId: stop.GLEN_WAVERLEY, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const ALAMEIN: LineConfig = {
  id: line.ALAMEIN,
  name: "Alamein",
  code: null,
  tags: [],
  urlPath: "alamein",
  routes: [
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.ALAMEIN, type: "regular" },
        { stopId: stop.ASHBURTON, type: "regular" },
        { stopId: stop.BURWOOD, type: "regular" },
        { stopId: stop.HARTWELL, type: "regular" },
        { stopId: stop.WILLISON, type: "regular" },
        { stopId: stop.RIVERSDALE, type: "regular" },
        { stopId: stop.CAMBERWELL, type: "regular" },
        { stopId: stop.AUBURN, type: "regular" },
        { stopId: stop.GLENFERRIE, type: "regular" },
        { stopId: stop.HAWTHORN, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.HAWTHORN, type: "regular" },
        { stopId: stop.GLENFERRIE, type: "regular" },
        { stopId: stop.AUBURN, type: "regular" },
        { stopId: stop.CAMBERWELL, type: "regular" },
        { stopId: stop.RIVERSDALE, type: "regular" },
        { stopId: stop.WILLISON, type: "regular" },
        { stopId: stop.HARTWELL, type: "regular" },
        { stopId: stop.BURWOOD, type: "regular" },
        { stopId: stop.ASHBURTON, type: "regular" },
        { stopId: stop.ALAMEIN, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const BELGRAVE: LineConfig = {
  id: line.BELGRAVE,
  name: "Belgrave",
  code: null,
  tags: [],
  urlPath: "belgrave",
  routes: [
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.BELGRAVE, type: "regular" },
        { stopId: stop.TECOMA, type: "regular" },
        { stopId: stop.UPWEY, type: "regular" },
        { stopId: stop.UPPER_FERNTREE_GULLY, type: "regular" },
        { stopId: stop.FERNTREE_GULLY, type: "regular" },
        { stopId: stop.BORONIA, type: "regular" },
        { stopId: stop.BAYSWATER, type: "regular" },
        { stopId: stop.HEATHMONT, type: "regular" },
        { stopId: stop.RINGWOOD, type: "regular" },
        { stopId: stop.HEATHERDALE, type: "regular" },
        { stopId: stop.MITCHAM, type: "regular" },
        { stopId: stop.NUNAWADING, type: "regular" },
        { stopId: stop.BLACKBURN, type: "regular" },
        { stopId: stop.LABURNUM, type: "regular" },
        { stopId: stop.BOX_HILL, type: "regular" },
        { stopId: stop.UNION, type: "regular" },
        { stopId: stop.CHATHAM, type: "regular" },
        { stopId: stop.CANTERBURY, type: "regular" },
        { stopId: stop.EAST_CAMBERWELL, type: "regular" },
        { stopId: stop.CAMBERWELL, type: "regular" },
        { stopId: stop.AUBURN, type: "regular" },
        { stopId: stop.GLENFERRIE, type: "regular" },
        { stopId: stop.HAWTHORN, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.HAWTHORN, type: "regular" },
        { stopId: stop.GLENFERRIE, type: "regular" },
        { stopId: stop.AUBURN, type: "regular" },
        { stopId: stop.CAMBERWELL, type: "regular" },
        { stopId: stop.EAST_CAMBERWELL, type: "regular" },
        { stopId: stop.CANTERBURY, type: "regular" },
        { stopId: stop.CHATHAM, type: "regular" },
        { stopId: stop.UNION, type: "regular" },
        { stopId: stop.BOX_HILL, type: "regular" },
        { stopId: stop.LABURNUM, type: "regular" },
        { stopId: stop.BLACKBURN, type: "regular" },
        { stopId: stop.NUNAWADING, type: "regular" },
        { stopId: stop.MITCHAM, type: "regular" },
        { stopId: stop.HEATHERDALE, type: "regular" },
        { stopId: stop.RINGWOOD, type: "regular" },
        { stopId: stop.HEATHMONT, type: "regular" },
        { stopId: stop.BAYSWATER, type: "regular" },
        { stopId: stop.BORONIA, type: "regular" },
        { stopId: stop.FERNTREE_GULLY, type: "regular" },
        { stopId: stop.UPPER_FERNTREE_GULLY, type: "regular" },
        { stopId: stop.UPWEY, type: "regular" },
        { stopId: stop.TECOMA, type: "regular" },
        { stopId: stop.BELGRAVE, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const LILYDALE: LineConfig = {
  id: line.LILYDALE,
  name: "Lilydale",
  code: null,
  tags: [],
  urlPath: "lilydale",
  routes: [
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.LILYDALE, type: "regular" },
        { stopId: stop.MOOROOLBARK, type: "regular" },
        { stopId: stop.CROYDON, type: "regular" },
        { stopId: stop.RINGWOOD_EAST, type: "regular" },
        { stopId: stop.RINGWOOD, type: "regular" },
        { stopId: stop.HEATHERDALE, type: "regular" },
        { stopId: stop.MITCHAM, type: "regular" },
        { stopId: stop.NUNAWADING, type: "regular" },
        { stopId: stop.BLACKBURN, type: "regular" },
        { stopId: stop.LABURNUM, type: "regular" },
        { stopId: stop.BOX_HILL, type: "regular" },
        { stopId: stop.UNION, type: "regular" },
        { stopId: stop.CHATHAM, type: "regular" },
        { stopId: stop.CANTERBURY, type: "regular" },
        { stopId: stop.EAST_CAMBERWELL, type: "regular" },
        { stopId: stop.CAMBERWELL, type: "regular" },
        { stopId: stop.AUBURN, type: "regular" },
        { stopId: stop.GLENFERRIE, type: "regular" },
        { stopId: stop.HAWTHORN, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.EAST_RICHMOND, type: "regular" },
        { stopId: stop.BURNLEY, type: "regular" },
        { stopId: stop.HAWTHORN, type: "regular" },
        { stopId: stop.GLENFERRIE, type: "regular" },
        { stopId: stop.AUBURN, type: "regular" },
        { stopId: stop.CAMBERWELL, type: "regular" },
        { stopId: stop.EAST_CAMBERWELL, type: "regular" },
        { stopId: stop.CANTERBURY, type: "regular" },
        { stopId: stop.CHATHAM, type: "regular" },
        { stopId: stop.UNION, type: "regular" },
        { stopId: stop.BOX_HILL, type: "regular" },
        { stopId: stop.LABURNUM, type: "regular" },
        { stopId: stop.BLACKBURN, type: "regular" },
        { stopId: stop.NUNAWADING, type: "regular" },
        { stopId: stop.MITCHAM, type: "regular" },
        { stopId: stop.HEATHERDALE, type: "regular" },
        { stopId: stop.RINGWOOD, type: "regular" },
        { stopId: stop.RINGWOOD_EAST, type: "regular" },
        { stopId: stop.CROYDON, type: "regular" },
        { stopId: stop.MOOROOLBARK, type: "regular" },
        { stopId: stop.LILYDALE, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const HURSTBRIDGE: LineConfig = {
  id: line.HURSTBRIDGE,
  name: "Hurstbridge",
  code: null,
  tags: [],
  urlPath: "hurstbridge",
  routes: [
    {
      id: route.UP_DIRECT,
      name: "Up Direct",
      tags: [],
      stops: [
        { stopId: stop.HURSTBRIDGE, type: "regular" },
        { stopId: stop.WATTLE_GLEN, type: "regular" },
        { stopId: stop.DIAMOND_CREEK, type: "regular" },
        { stopId: stop.ELTHAM, type: "regular" },
        { stopId: stop.MONTMORENCY, type: "regular" },
        { stopId: stop.GREENSBOROUGH, type: "regular" },
        { stopId: stop.WATSONIA, type: "regular" },
        { stopId: stop.MACLEOD, type: "regular" },
        { stopId: stop.ROSANNA, type: "regular" },
        { stopId: stop.HEIDELBERG, type: "regular" },
        { stopId: stop.EAGLEMONT, type: "regular" },
        { stopId: stop.IVANHOE, type: "regular" },
        { stopId: stop.DAREBIN, type: "regular" },
        { stopId: stop.ALPHINGTON, type: "regular" },
        { stopId: stop.FAIRFIELD, type: "regular" },
        { stopId: stop.DENNIS, type: "regular" },
        { stopId: stop.WESTGARTH, type: "regular" },
        { stopId: stop.CLIFTON_HILL, type: "regular" },
        { stopId: stop.VICTORIA_PARK, type: "regular" },
        { stopId: stop.COLLINGWOOD, type: "regular" },
        { stopId: stop.NORTH_RICHMOND, type: "regular" },
        { stopId: stop.WEST_RICHMOND, type: "regular" },
        { stopId: stop.JOLIMONT, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.JOLIMONT, type: "regular" },
        { stopId: stop.WEST_RICHMOND, type: "regular" },
        { stopId: stop.NORTH_RICHMOND, type: "regular" },
        { stopId: stop.COLLINGWOOD, type: "regular" },
        { stopId: stop.VICTORIA_PARK, type: "regular" },
        { stopId: stop.CLIFTON_HILL, type: "regular" },
        { stopId: stop.WESTGARTH, type: "regular" },
        { stopId: stop.DENNIS, type: "regular" },
        { stopId: stop.FAIRFIELD, type: "regular" },
        { stopId: stop.ALPHINGTON, type: "regular" },
        { stopId: stop.DAREBIN, type: "regular" },
        { stopId: stop.IVANHOE, type: "regular" },
        { stopId: stop.EAGLEMONT, type: "regular" },
        { stopId: stop.HEIDELBERG, type: "regular" },
        { stopId: stop.ROSANNA, type: "regular" },
        { stopId: stop.MACLEOD, type: "regular" },
        { stopId: stop.WATSONIA, type: "regular" },
        { stopId: stop.GREENSBOROUGH, type: "regular" },
        { stopId: stop.MONTMORENCY, type: "regular" },
        { stopId: stop.ELTHAM, type: "regular" },
        { stopId: stop.DIAMOND_CREEK, type: "regular" },
        { stopId: stop.WATTLE_GLEN, type: "regular" },
        { stopId: stop.HURSTBRIDGE, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const MERNDA: LineConfig = {
  id: line.MERNDA,
  name: "Mernda",
  code: null,
  tags: [],
  urlPath: "mernda",
  routes: [
    {
      id: route.UP_DIRECT,
      name: "Up Direct",
      tags: [],
      stops: [
        { stopId: stop.MERNDA, type: "regular" },
        { stopId: stop.HAWKSTOWE, type: "regular" },
        { stopId: stop.MIDDLE_GORGE, type: "regular" },
        { stopId: stop.SOUTH_MORANG, type: "regular" },
        { stopId: stop.EPPING, type: "regular" },
        { stopId: stop.LALOR, type: "regular" },
        { stopId: stop.THOMASTOWN, type: "regular" },
        { stopId: stop.KEON_PARK, type: "regular" },
        { stopId: stop.RUTHVEN, type: "regular" },
        { stopId: stop.RESERVOIR, type: "regular" },
        { stopId: stop.REGENT, type: "regular" },
        { stopId: stop.PRESTON, type: "regular" },
        { stopId: stop.BELL, type: "regular" },
        { stopId: stop.THORNBURY, type: "regular" },
        { stopId: stop.CROXTON, type: "regular" },
        { stopId: stop.NORTHCOTE, type: "regular" },
        { stopId: stop.MERRI, type: "regular" },
        { stopId: stop.RUSHALL, type: "regular" },
        { stopId: stop.CLIFTON_HILL, type: "regular" },
        { stopId: stop.VICTORIA_PARK, type: "regular" },
        { stopId: stop.COLLINGWOOD, type: "regular" },
        { stopId: stop.NORTH_RICHMOND, type: "regular" },
        { stopId: stop.WEST_RICHMOND, type: "regular" },
        { stopId: stop.JOLIMONT, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.JOLIMONT, type: "regular" },
        { stopId: stop.WEST_RICHMOND, type: "regular" },
        { stopId: stop.NORTH_RICHMOND, type: "regular" },
        { stopId: stop.COLLINGWOOD, type: "regular" },
        { stopId: stop.VICTORIA_PARK, type: "regular" },
        { stopId: stop.CLIFTON_HILL, type: "regular" },
        { stopId: stop.RUSHALL, type: "regular" },
        { stopId: stop.MERRI, type: "regular" },
        { stopId: stop.NORTHCOTE, type: "regular" },
        { stopId: stop.CROXTON, type: "regular" },
        { stopId: stop.THORNBURY, type: "regular" },
        { stopId: stop.BELL, type: "regular" },
        { stopId: stop.PRESTON, type: "regular" },
        { stopId: stop.REGENT, type: "regular" },
        { stopId: stop.RESERVOIR, type: "regular" },
        { stopId: stop.RUTHVEN, type: "regular" },
        { stopId: stop.KEON_PARK, type: "regular" },
        { stopId: stop.THOMASTOWN, type: "regular" },
        { stopId: stop.LALOR, type: "regular" },
        { stopId: stop.EPPING, type: "regular" },
        { stopId: stop.SOUTH_MORANG, type: "regular" },
        { stopId: stop.MIDDLE_GORGE, type: "regular" },
        { stopId: stop.HAWKSTOWE, type: "regular" },
        { stopId: stop.MERNDA, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const UPFIELD: LineConfig = {
  id: line.UPFIELD,
  name: "Upfield",
  code: null,
  tags: [],
  urlPath: "upfield",
  routes: [
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.MACAULAY, type: "regular" },
        { stopId: stop.FLEMINGTON_BRIDGE, type: "regular" },
        { stopId: stop.ROYAL_PARK, type: "regular" },
        { stopId: stop.JEWELL, type: "regular" },
        { stopId: stop.BRUNSWICK, type: "regular" },
        { stopId: stop.ANSTEY, type: "regular" },
        { stopId: stop.MORELAND, type: "regular" },
        { stopId: stop.COBURG, type: "regular" },
        { stopId: stop.BATMAN, type: "regular" },
        { stopId: stop.MERLYNSTON, type: "regular" },
        { stopId: stop.FAWKNER, type: "regular" },
        { stopId: stop.GOWRIE, type: "regular" },
        { stopId: stop.UPFIELD, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_DIRECT,
      name: "Up Direct",
      tags: [],
      stops: [
        { stopId: stop.UPFIELD, type: "regular" },
        { stopId: stop.GOWRIE, type: "regular" },
        { stopId: stop.FAWKNER, type: "regular" },
        { stopId: stop.MERLYNSTON, type: "regular" },
        { stopId: stop.BATMAN, type: "regular" },
        { stopId: stop.COBURG, type: "regular" },
        { stopId: stop.MORELAND, type: "regular" },
        { stopId: stop.ANSTEY, type: "regular" },
        { stopId: stop.BRUNSWICK, type: "regular" },
        { stopId: stop.JEWELL, type: "regular" },
        { stopId: stop.ROYAL_PARK, type: "regular" },
        { stopId: stop.FLEMINGTON_BRIDGE, type: "regular" },
        { stopId: stop.MACAULAY, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.UPFIELD, type: "regular" },
        { stopId: stop.GOWRIE, type: "regular" },
        { stopId: stop.FAWKNER, type: "regular" },
        { stopId: stop.MERLYNSTON, type: "regular" },
        { stopId: stop.BATMAN, type: "regular" },
        { stopId: stop.COBURG, type: "regular" },
        { stopId: stop.MORELAND, type: "regular" },
        { stopId: stop.ANSTEY, type: "regular" },
        { stopId: stop.BRUNSWICK, type: "regular" },
        { stopId: stop.JEWELL, type: "regular" },
        { stopId: stop.ROYAL_PARK, type: "regular" },
        { stopId: stop.FLEMINGTON_BRIDGE, type: "regular" },
        { stopId: stop.MACAULAY, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.MACAULAY, type: "regular" },
        { stopId: stop.FLEMINGTON_BRIDGE, type: "regular" },
        { stopId: stop.ROYAL_PARK, type: "regular" },
        { stopId: stop.JEWELL, type: "regular" },
        { stopId: stop.BRUNSWICK, type: "regular" },
        { stopId: stop.ANSTEY, type: "regular" },
        { stopId: stop.MORELAND, type: "regular" },
        { stopId: stop.COBURG, type: "regular" },
        { stopId: stop.BATMAN, type: "regular" },
        { stopId: stop.MERLYNSTON, type: "regular" },
        { stopId: stop.FAWKNER, type: "regular" },
        { stopId: stop.GOWRIE, type: "regular" },
        { stopId: stop.UPFIELD, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const CRAIGIEBURN: LineConfig = {
  id: line.CRAIGIEBURN,
  name: "Craigieburn",
  code: null,
  tags: [],
  urlPath: "craigieburn",
  routes: [
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.KENSINGTON, type: "regular" },
        { stopId: stop.NEWMARKET, type: "regular" },
        { stopId: stop.ASCOT_VALE, type: "regular" },
        { stopId: stop.MOONEE_PONDS, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.GLENBERVIE, type: "regular" },
        { stopId: stop.STRATHMORE, type: "regular" },
        { stopId: stop.PASCOE_VALE, type: "regular" },
        { stopId: stop.OAK_PARK, type: "regular" },
        { stopId: stop.GLENROY, type: "regular" },
        { stopId: stop.JACANA, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.COOLAROO, type: "regular" },
        { stopId: stop.ROXBURGH_PARK, type: "regular" },
        { stopId: stop.CRAIGIEBURN, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_DIRECT,
      name: "Up Direct",
      tags: [],
      stops: [
        { stopId: stop.CRAIGIEBURN, type: "regular" },
        { stopId: stop.ROXBURGH_PARK, type: "regular" },
        { stopId: stop.COOLAROO, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.JACANA, type: "regular" },
        { stopId: stop.GLENROY, type: "regular" },
        { stopId: stop.OAK_PARK, type: "regular" },
        { stopId: stop.PASCOE_VALE, type: "regular" },
        { stopId: stop.STRATHMORE, type: "regular" },
        { stopId: stop.GLENBERVIE, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.MOONEE_PONDS, type: "regular" },
        { stopId: stop.ASCOT_VALE, type: "regular" },
        { stopId: stop.NEWMARKET, type: "regular" },
        { stopId: stop.KENSINGTON, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.CRAIGIEBURN, type: "regular" },
        { stopId: stop.ROXBURGH_PARK, type: "regular" },
        { stopId: stop.COOLAROO, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.JACANA, type: "regular" },
        { stopId: stop.GLENROY, type: "regular" },
        { stopId: stop.OAK_PARK, type: "regular" },
        { stopId: stop.PASCOE_VALE, type: "regular" },
        { stopId: stop.STRATHMORE, type: "regular" },
        { stopId: stop.GLENBERVIE, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.MOONEE_PONDS, type: "regular" },
        { stopId: stop.ASCOT_VALE, type: "regular" },
        { stopId: stop.NEWMARKET, type: "regular" },
        { stopId: stop.KENSINGTON, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.KENSINGTON, type: "regular" },
        { stopId: stop.NEWMARKET, type: "regular" },
        { stopId: stop.ASCOT_VALE, type: "regular" },
        { stopId: stop.MOONEE_PONDS, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.GLENBERVIE, type: "regular" },
        { stopId: stop.STRATHMORE, type: "regular" },
        { stopId: stop.PASCOE_VALE, type: "regular" },
        { stopId: stop.OAK_PARK, type: "regular" },
        { stopId: stop.GLENROY, type: "regular" },
        { stopId: stop.JACANA, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.COOLAROO, type: "regular" },
        { stopId: stop.ROXBURGH_PARK, type: "regular" },
        { stopId: stop.CRAIGIEBURN, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const SEYMOUR: LineConfig = {
  id: line.SEYMOUR,
  name: "Seymour",
  code: null,
  tags: [],
  urlPath: "seymour",
  routes: [
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.CRAIGIEBURN, type: "regular" },
        { stopId: stop.DONNYBROOK, type: "regular" },
        { stopId: stop.WALLAN, type: "regular" },
        { stopId: stop.HEATHCOTE_JUNCTION, type: "regular" },
        { stopId: stop.WANDONG, type: "regular" },
        { stopId: stop.KILMORE_EAST, type: "regular" },
        { stopId: stop.BROADFORD, type: "regular" },
        { stopId: stop.TALLAROOK, type: "regular" },
        { stopId: stop.SEYMOUR, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.SEYMOUR, type: "regular" },
        { stopId: stop.TALLAROOK, type: "regular" },
        { stopId: stop.BROADFORD, type: "regular" },
        { stopId: stop.KILMORE_EAST, type: "regular" },
        { stopId: stop.WANDONG, type: "regular" },
        { stopId: stop.HEATHCOTE_JUNCTION, type: "regular" },
        { stopId: stop.WALLAN, type: "regular" },
        { stopId: stop.DONNYBROOK, type: "regular" },
        { stopId: stop.CRAIGIEBURN, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const FLEMINGTON_RACECOURSE: LineConfig = {
  id: line.FLEMINGTON_RACECOURSE,
  name: "Flemington Racecourse",
  code: null,
  tags: [],
  urlPath: "flemingtonracecourse",
  routes: [
    {
      id: route.UP_DIRECT,
      name: "Up Direct",
      tags: [],
      stops: [
        { stopId: stop.FLEMINGTON_RACECOURSE, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FLEMINGTON_RACECOURSE, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const SUNBURY: LineConfig = {
  id: line.SUNBURY,
  name: "Sunbury",
  code: null,
  tags: [],
  urlPath: "sunbury",
  routes: [
    {
      id: route.DOWN_VIA_METRO_TUNNEL,
      name: "Down via Metro Tunnel",
      tags: [],
      stops: [
        { stopId: stop.TOWN_HALL, type: "regular" },
        { stopId: stop.STATE_LIBRARY, type: "regular" },
        { stopId: stop.PARKVILLE, type: "regular" },
        { stopId: stop.ARDEN, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.MIDDLE_FOOTSCRAY, type: "regular" },
        { stopId: stop.WEST_FOOTSCRAY, type: "regular" },
        { stopId: stop.TOTTENHAM, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.ALBION, type: "regular" },
        { stopId: stop.GINIFER, type: "regular" },
        { stopId: stop.ST_ALBANS, type: "regular" },
        { stopId: stop.KEILOR_PLAINS, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.DIGGERS_REST, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_METRO_TUNNEL,
      name: "Up via Metro Tunnel",
      tags: [],
      stops: [
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.DIGGERS_REST, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.KEILOR_PLAINS, type: "regular" },
        { stopId: stop.ST_ALBANS, type: "regular" },
        { stopId: stop.GINIFER, type: "regular" },
        { stopId: stop.ALBION, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.TOTTENHAM, type: "regular" },
        { stopId: stop.WEST_FOOTSCRAY, type: "regular" },
        { stopId: stop.MIDDLE_FOOTSCRAY, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.ARDEN, type: "regular" },
        { stopId: stop.PARKVILLE, type: "regular" },
        { stopId: stop.STATE_LIBRARY, type: "regular" },
        { stopId: stop.TOWN_HALL, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_DIRECT,
      name: "Up Direct",
      tags: [],
      stops: [
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.DIGGERS_REST, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.KEILOR_PLAINS, type: "regular" },
        { stopId: stop.ST_ALBANS, type: "regular" },
        { stopId: stop.GINIFER, type: "regular" },
        { stopId: stop.ALBION, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.TOTTENHAM, type: "regular" },
        { stopId: stop.WEST_FOOTSCRAY, type: "regular" },
        { stopId: stop.MIDDLE_FOOTSCRAY, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_DIRECT,
      name: "Down Direct",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.MIDDLE_FOOTSCRAY, type: "regular" },
        { stopId: stop.WEST_FOOTSCRAY, type: "regular" },
        { stopId: stop.TOTTENHAM, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.ALBION, type: "regular" },
        { stopId: stop.GINIFER, type: "regular" },
        { stopId: stop.ST_ALBANS, type: "regular" },
        { stopId: stop.KEILOR_PLAINS, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.DIGGERS_REST, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP_VIA_CITY_LOOP,
      name: "Up via City Loop",
      tags: [],
      stops: [
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.DIGGERS_REST, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.KEILOR_PLAINS, type: "regular" },
        { stopId: stop.ST_ALBANS, type: "regular" },
        { stopId: stop.GINIFER, type: "regular" },
        { stopId: stop.ALBION, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.TOTTENHAM, type: "regular" },
        { stopId: stop.WEST_FOOTSCRAY, type: "regular" },
        { stopId: stop.MIDDLE_FOOTSCRAY, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN_VIA_CITY_LOOP,
      name: "Down via City Loop",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.PARLIAMENT, type: "regular" },
        { stopId: stop.MELBOURNE_CENTRAL, type: "regular" },
        { stopId: stop.FLAGSTAFF, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.MIDDLE_FOOTSCRAY, type: "regular" },
        { stopId: stop.WEST_FOOTSCRAY, type: "regular" },
        { stopId: stop.TOTTENHAM, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.ALBION, type: "regular" },
        { stopId: stop.GINIFER, type: "regular" },
        { stopId: stop.ST_ALBANS, type: "regular" },
        { stopId: stop.KEILOR_PLAINS, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.DIGGERS_REST, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const BENDIGO: LineConfig = {
  id: line.BENDIGO,
  name: "Bendigo",
  code: null,
  tags: [],
  urlPath: "bendigo",
  routes: [
    {
      id: route.ROUTE_1,
      name: "Route 1",
      tags: [],
      stops: [
        { stopId: stop.EAGLEHAWK, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_2,
      name: "Route 2",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.EAGLEHAWK, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_3,
      name: "Route 3",
      tags: [],
      stops: [
        { stopId: stop.EPSOM, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_4,
      name: "Route 4",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.EPSOM, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_5,
      name: "Route 5",
      tags: [],
      stops: [
        { stopId: stop.EPSOM, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_6,
      name: "Route 6",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.EPSOM, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const BALLARAT: LineConfig = {
  id: line.BALLARAT,
  name: "Ballarat",
  code: null,
  tags: [],
  urlPath: "ballarat",
  routes: [
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.ARDEER, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.CAROLINE_SPRINGS, type: "regular" },
        { stopId: stop.ROCKBANK, type: "regular" },
        { stopId: stop.COBBLEBANK, type: "regular" },
        { stopId: stop.MELTON, type: "regular" },
        { stopId: stop.BACCHUS_MARSH, type: "regular" },
        { stopId: stop.BALLAN, type: "regular" },
        { stopId: stop.BALLARAT, type: "regular" },
        { stopId: stop.WENDOUREE, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.WENDOUREE, type: "regular" },
        { stopId: stop.BALLARAT, type: "regular" },
        { stopId: stop.BALLAN, type: "regular" },
        { stopId: stop.BACCHUS_MARSH, type: "regular" },
        { stopId: stop.MELTON, type: "regular" },
        { stopId: stop.COBBLEBANK, type: "regular" },
        { stopId: stop.ROCKBANK, type: "regular" },
        { stopId: stop.CAROLINE_SPRINGS, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.ARDEER, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const GEELONG: LineConfig = {
  id: line.GEELONG,
  name: "Geelong",
  code: null,
  tags: [],
  urlPath: "geelong",
  routes: [
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.TARNEIT, type: "regular" },
        { stopId: stop.WYNDHAM_VALE, type: "regular" },
        { stopId: stop.LITTLE_RIVER, type: "regular" },
        { stopId: stop.LARA, type: "regular" },
        { stopId: stop.CORIO, type: "regular" },
        { stopId: stop.NORTH_SHORE, type: "regular" },
        { stopId: stop.NORTH_GEELONG, type: "regular" },
        { stopId: stop.GEELONG, type: "regular" },
        { stopId: stop.SOUTH_GEELONG, type: "regular" },
        { stopId: stop.MARSHALL, type: "regular" },
        { stopId: stop.WAURN_PONDS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.WAURN_PONDS, type: "regular" },
        { stopId: stop.MARSHALL, type: "regular" },
        { stopId: stop.SOUTH_GEELONG, type: "regular" },
        { stopId: stop.GEELONG, type: "regular" },
        { stopId: stop.NORTH_GEELONG, type: "regular" },
        { stopId: stop.NORTH_SHORE, type: "regular" },
        { stopId: stop.CORIO, type: "regular" },
        { stopId: stop.LARA, type: "regular" },
        { stopId: stop.LITTLE_RIVER, type: "regular" },
        { stopId: stop.WYNDHAM_VALE, type: "regular" },
        { stopId: stop.TARNEIT, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const WERRIBEE: LineConfig = {
  id: line.WERRIBEE,
  name: "Werribee",
  code: null,
  tags: [],
  urlPath: "werribee",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.WERRIBEE, type: "regular" },
        { stopId: stop.HOPPERS_CROSSING, type: "regular" },
        { stopId: stop.WILLIAMS_LANDING, type: "regular" },
        { stopId: stop.AIRCRAFT, type: "regular" },
        { stopId: stop.LAVERTON, type: "regular" },
        { stopId: stop.WESTONA, type: "regular" },
        { stopId: stop.ALTONA, type: "regular" },
        { stopId: stop.SEAHOLME, type: "regular" },
        { stopId: stop.NEWPORT, type: "regular" },
        { stopId: stop.SPOTSWOOD, type: "regular" },
        { stopId: stop.YARRAVILLE, type: "regular" },
        { stopId: stop.SEDDON, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTH_KENSINGTON, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTH_KENSINGTON, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SEDDON, type: "regular" },
        { stopId: stop.YARRAVILLE, type: "regular" },
        { stopId: stop.SPOTSWOOD, type: "regular" },
        { stopId: stop.NEWPORT, type: "regular" },
        { stopId: stop.SEAHOLME, type: "regular" },
        { stopId: stop.ALTONA, type: "regular" },
        { stopId: stop.WESTONA, type: "regular" },
        { stopId: stop.LAVERTON, type: "regular" },
        { stopId: stop.AIRCRAFT, type: "regular" },
        { stopId: stop.WILLIAMS_LANDING, type: "regular" },
        { stopId: stop.HOPPERS_CROSSING, type: "regular" },
        { stopId: stop.WERRIBEE, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const WILLIAMSTOWN: LineConfig = {
  id: line.WILLIAMSTOWN,
  name: "Williamstown",
  code: null,
  tags: [],
  urlPath: "williamstown",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.WILLIAMSTOWN, type: "regular" },
        { stopId: stop.WILLIAMSTOWN_BEACH, type: "regular" },
        { stopId: stop.NORTH_WILLIAMSTOWN, type: "regular" },
        { stopId: stop.NEWPORT, type: "regular" },
        { stopId: stop.SPOTSWOOD, type: "regular" },
        { stopId: stop.YARRAVILLE, type: "regular" },
        { stopId: stop.SEDDON, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTH_KENSINGTON, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTH_KENSINGTON, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SEDDON, type: "regular" },
        { stopId: stop.YARRAVILLE, type: "regular" },
        { stopId: stop.SPOTSWOOD, type: "regular" },
        { stopId: stop.NEWPORT, type: "regular" },
        { stopId: stop.NORTH_WILLIAMSTOWN, type: "regular" },
        { stopId: stop.WILLIAMSTOWN_BEACH, type: "regular" },
        { stopId: stop.WILLIAMSTOWN, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const ALBURY: LineConfig = {
  id: line.ALBURY,
  name: "Albury",
  code: null,
  tags: [],
  urlPath: "albury",
  routes: [
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.SEYMOUR, type: "regular" },
        { stopId: stop.AVENEL, type: "regular" },
        { stopId: stop.EUROA, type: "regular" },
        { stopId: stop.VIOLET_TOWN, type: "regular" },
        { stopId: stop.BENALLA, type: "regular" },
        { stopId: stop.WANGARATTA, type: "regular" },
        { stopId: stop.SPRINGHURST, type: "regular" },
        { stopId: stop.CHILTERN, type: "regular" },
        { stopId: stop.WODONGA, type: "regular" },
        { stopId: stop.ALBURY, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.ALBURY, type: "regular" },
        { stopId: stop.WODONGA, type: "regular" },
        { stopId: stop.CHILTERN, type: "regular" },
        { stopId: stop.SPRINGHURST, type: "regular" },
        { stopId: stop.WANGARATTA, type: "regular" },
        { stopId: stop.BENALLA, type: "regular" },
        { stopId: stop.VIOLET_TOWN, type: "regular" },
        { stopId: stop.EUROA, type: "regular" },
        { stopId: stop.AVENEL, type: "regular" },
        { stopId: stop.SEYMOUR, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const ARARAT: LineConfig = {
  id: line.ARARAT,
  name: "Ararat",
  code: null,
  tags: [],
  urlPath: "ararat",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.ARARAT, type: "regular" },
        { stopId: stop.BEAUFORT, type: "regular" },
        { stopId: stop.WENDOUREE, type: "regular" },
        { stopId: stop.BALLARAT, type: "regular" },
        { stopId: stop.BALLAN, type: "regular" },
        { stopId: stop.BACCHUS_MARSH, type: "regular" },
        { stopId: stop.MELTON, type: "regular" },
        { stopId: stop.COBBLEBANK, type: "regular" },
        { stopId: stop.ROCKBANK, type: "regular" },
        { stopId: stop.CAROLINE_SPRINGS, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.ARDEER, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.ARDEER, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.CAROLINE_SPRINGS, type: "regular" },
        { stopId: stop.ROCKBANK, type: "regular" },
        { stopId: stop.COBBLEBANK, type: "regular" },
        { stopId: stop.MELTON, type: "regular" },
        { stopId: stop.BACCHUS_MARSH, type: "regular" },
        { stopId: stop.BALLAN, type: "regular" },
        { stopId: stop.BALLARAT, type: "regular" },
        { stopId: stop.WENDOUREE, type: "regular" },
        { stopId: stop.BEAUFORT, type: "regular" },
        { stopId: stop.ARARAT, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const BAIRNSDALE: LineConfig = {
  id: line.BAIRNSDALE,
  name: "Bairnsdale",
  code: null,
  tags: [],
  urlPath: "bairnsdale",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.BAIRNSDALE, type: "regular" },
        { stopId: stop.STRATFORD, type: "regular" },
        { stopId: stop.SALE, type: "regular" },
        { stopId: stop.ROSEDALE, type: "regular" },
        { stopId: stop.TRARALGON, type: "regular" },
        { stopId: stop.MORWELL, type: "regular" },
        { stopId: stop.MOE, type: "regular" },
        { stopId: stop.TRAFALGAR, type: "regular" },
        { stopId: stop.YARRAGON, type: "regular" },
        { stopId: stop.WARRAGUL, type: "regular" },
        { stopId: stop.DROUIN, type: "regular" },
        { stopId: stop.LONGWARRY, type: "regular" },
        { stopId: stop.BUNYIP, type: "regular" },
        { stopId: stop.GARFIELD, type: "regular" },
        { stopId: stop.TYNONG, type: "regular" },
        { stopId: stop.NAR_NAR_GOON, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FLINDERS_STREET, type: "regular" },
        { stopId: stop.RICHMOND, type: "regular" },
        { stopId: stop.CAULFIELD, type: "regular" },
        { stopId: stop.CLAYTON, type: "regular" },
        { stopId: stop.DANDENONG, type: "regular" },
        { stopId: stop.PAKENHAM, type: "regular" },
        { stopId: stop.NAR_NAR_GOON, type: "regular" },
        { stopId: stop.TYNONG, type: "regular" },
        { stopId: stop.GARFIELD, type: "regular" },
        { stopId: stop.BUNYIP, type: "regular" },
        { stopId: stop.LONGWARRY, type: "regular" },
        { stopId: stop.DROUIN, type: "regular" },
        { stopId: stop.WARRAGUL, type: "regular" },
        { stopId: stop.YARRAGON, type: "regular" },
        { stopId: stop.TRAFALGAR, type: "regular" },
        { stopId: stop.MOE, type: "regular" },
        { stopId: stop.MORWELL, type: "regular" },
        { stopId: stop.TRARALGON, type: "regular" },
        { stopId: stop.ROSEDALE, type: "regular" },
        { stopId: stop.SALE, type: "regular" },
        { stopId: stop.STRATFORD, type: "regular" },
        { stopId: stop.BAIRNSDALE, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const ECHUCA: LineConfig = {
  id: line.ECHUCA,
  name: "Echuca",
  code: null,
  tags: [],
  urlPath: "echuca",
  routes: [
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.EPSOM, type: "regular" },
        { stopId: stop.HUNTLY, type: "regular" },
        { stopId: stop.GOORNONG, type: "regular" },
        { stopId: stop.ELMORE, type: "regular" },
        { stopId: stop.ROCHESTER, type: "regular" },
        { stopId: stop.ECHUCA, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.ECHUCA, type: "regular" },
        { stopId: stop.ROCHESTER, type: "regular" },
        { stopId: stop.ELMORE, type: "regular" },
        { stopId: stop.GOORNONG, type: "regular" },
        { stopId: stop.HUNTLY, type: "regular" },
        { stopId: stop.EPSOM, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.MACEDON, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.RIDDELLS_CREEK, type: "regular" },
        { stopId: stop.CLARKEFIELD, type: "regular" },
        { stopId: stop.SUNBURY, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const MARYBOROUGH: LineConfig = {
  id: line.MARYBOROUGH,
  name: "Maryborough",
  code: null,
  tags: [],
  urlPath: "maryborough",
  routes: [
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.ARDEER, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.CAROLINE_SPRINGS, type: "regular" },
        { stopId: stop.ROCKBANK, type: "regular" },
        { stopId: stop.COBBLEBANK, type: "regular" },
        { stopId: stop.MELTON, type: "regular" },
        { stopId: stop.BACCHUS_MARSH, type: "regular" },
        { stopId: stop.BALLAN, type: "regular" },
        { stopId: stop.BALLARAT, type: "regular" },
        { stopId: stop.CRESWICK, type: "regular" },
        { stopId: stop.CLUNES, type: "regular" },
        { stopId: stop.TALBOT, type: "regular" },
        { stopId: stop.MARYBOROUGH, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.MARYBOROUGH, type: "regular" },
        { stopId: stop.TALBOT, type: "regular" },
        { stopId: stop.CLUNES, type: "regular" },
        { stopId: stop.CRESWICK, type: "regular" },
        { stopId: stop.BALLARAT, type: "regular" },
        { stopId: stop.BALLAN, type: "regular" },
        { stopId: stop.BACCHUS_MARSH, type: "regular" },
        { stopId: stop.MELTON, type: "regular" },
        { stopId: stop.COBBLEBANK, type: "regular" },
        { stopId: stop.ROCKBANK, type: "regular" },
        { stopId: stop.CAROLINE_SPRINGS, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.ARDEER, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const SHEPPARTON: LineConfig = {
  id: line.SHEPPARTON,
  name: "Shepparton",
  code: null,
  tags: [],
  urlPath: "shepparton",
  routes: [
    {
      id: route.ROUTE_1,
      name: "Route 1",
      tags: [],
      stops: [
        { stopId: stop.SHEPPARTON, type: "regular" },
        { stopId: stop.MOOROOPNA, type: "regular" },
        { stopId: stop.MURCHISON_EAST, type: "regular" },
        { stopId: stop.NAGAMBIE, type: "regular" },
        { stopId: stop.SEYMOUR, type: "regular" },
        { stopId: stop.TALLAROOK, type: "regular" },
        { stopId: stop.BROADFORD, type: "regular" },
        { stopId: stop.KILMORE_EAST, type: "regular" },
        { stopId: stop.WANDONG, type: "regular" },
        { stopId: stop.HEATHCOTE_JUNCTION, type: "regular" },
        { stopId: stop.WALLAN, type: "regular" },
        { stopId: stop.DONNYBROOK, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_2,
      name: "Route 2",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.NORTH_MELBOURNE, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.CRAIGIEBURN, type: "regular" },
        { stopId: stop.DONNYBROOK, type: "regular" },
        { stopId: stop.WALLAN, type: "regular" },
        { stopId: stop.HEATHCOTE_JUNCTION, type: "regular" },
        { stopId: stop.WANDONG, type: "regular" },
        { stopId: stop.KILMORE_EAST, type: "regular" },
        { stopId: stop.BROADFORD, type: "regular" },
        { stopId: stop.TALLAROOK, type: "regular" },
        { stopId: stop.SEYMOUR, type: "regular" },
        { stopId: stop.NAGAMBIE, type: "regular" },
        { stopId: stop.MURCHISON_EAST, type: "regular" },
        { stopId: stop.MOOROOPNA, type: "regular" },
        { stopId: stop.SHEPPARTON, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.ROUTE_3,
      name: "Route 3",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.ESSENDON, type: "regular" },
        { stopId: stop.BROADMEADOWS, type: "regular" },
        { stopId: stop.DONNYBROOK, type: "regular" },
        { stopId: stop.WALLAN, type: "regular" },
        { stopId: stop.WANDONG, type: "regular" },
        { stopId: stop.KILMORE_EAST, type: "regular" },
        { stopId: stop.BROADFORD, type: "regular" },
        { stopId: stop.SEYMOUR, type: "regular" },
        { stopId: stop.NAGAMBIE, type: "regular" },
        { stopId: stop.MURCHISON_EAST, type: "regular" },
        { stopId: stop.MOOROOPNA, type: "regular" },
        { stopId: stop.SHEPPARTON, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const SWAN_HILL: LineConfig = {
  id: line.SWAN_HILL,
  name: "Swan Hill",
  code: null,
  tags: [],
  urlPath: "swanhill",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.SWAN_HILL, type: "regular" },
        { stopId: stop.KERANG, type: "regular" },
        { stopId: stop.PYRAMID, type: "regular" },
        { stopId: stop.DINGEE, type: "regular" },
        { stopId: stop.RAYWOOD, type: "regular" },
        { stopId: stop.EAGLEHAWK, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.WATERGARDENS, type: "regular" },
        { stopId: stop.GISBORNE, type: "regular" },
        { stopId: stop.WOODEND, type: "regular" },
        { stopId: stop.KYNETON, type: "regular" },
        { stopId: stop.MALMSBURY, type: "regular" },
        { stopId: stop.CASTLEMAINE, type: "regular" },
        { stopId: stop.KANGAROO_FLAT, type: "regular" },
        { stopId: stop.BENDIGO, type: "regular" },
        { stopId: stop.EAGLEHAWK, type: "regular" },
        { stopId: stop.RAYWOOD, type: "regular" },
        { stopId: stop.DINGEE, type: "regular" },
        { stopId: stop.PYRAMID, type: "regular" },
        { stopId: stop.KERANG, type: "regular" },
        { stopId: stop.SWAN_HILL, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};

export const WARRNAMBOOL: LineConfig = {
  id: line.WARRNAMBOOL,
  name: "Warrnambool",
  code: null,
  tags: [],
  urlPath: "warrnambool",
  routes: [
    {
      id: route.UP,
      name: "Up",
      tags: [],
      stops: [
        { stopId: stop.WARRNAMBOOL, type: "regular" },
        { stopId: stop.SHERWOOD_PARK, type: "regular" },
        { stopId: stop.TERANG, type: "regular" },
        { stopId: stop.CAMPERDOWN, type: "regular" },
        { stopId: stop.COLAC, type: "regular" },
        { stopId: stop.BIRREGURRA, type: "regular" },
        { stopId: stop.WINCHELSEA, type: "regular" },
        { stopId: stop.WAURN_PONDS, type: "regular" },
        { stopId: stop.MARSHALL, type: "regular" },
        { stopId: stop.SOUTH_GEELONG, type: "regular" },
        { stopId: stop.GEELONG, type: "regular" },
        { stopId: stop.NORTH_GEELONG, type: "regular" },
        { stopId: stop.NORTH_SHORE, type: "regular" },
        { stopId: stop.CORIO, type: "regular" },
        { stopId: stop.LARA, type: "regular" },
        { stopId: stop.WYNDHAM_VALE, type: "regular" },
        { stopId: stop.TARNEIT, type: "regular" },
        { stopId: stop.DEER_PARK, type: "regular" },
        { stopId: stop.SUNSHINE, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
      ],
      color: null,
    },
    {
      id: route.DOWN,
      name: "Down",
      tags: [],
      stops: [
        { stopId: stop.SOUTHERN_CROSS, type: "regular" },
        { stopId: stop.FOOTSCRAY, type: "regular" },
        { stopId: stop.NORTH_GEELONG, type: "regular" },
        { stopId: stop.GEELONG, type: "regular" },
        { stopId: stop.SOUTH_GEELONG, type: "regular" },
        { stopId: stop.MARSHALL, type: "regular" },
        { stopId: stop.WAURN_PONDS, type: "regular" },
        { stopId: stop.WINCHELSEA, type: "regular" },
        { stopId: stop.BIRREGURRA, type: "regular" },
        { stopId: stop.COLAC, type: "regular" },
        { stopId: stop.CAMPERDOWN, type: "regular" },
        { stopId: stop.TERANG, type: "regular" },
        { stopId: stop.SHERWOOD_PARK, type: "regular" },
        { stopId: stop.WARRNAMBOOL, type: "regular" },
      ],
      color: null,
    },
  ],
  diagram: { entries: [] },
};
