export const UP = 1; // Up
export const DOWN = 2; // Down
// [REMOVED] export const UP_DIRECT = 3; // Up Direct
// [REMOVED] export const DOWN_DIRECT = 4; // Down Direct
// [REMOVED] export const UP_VIA_CITY_LOOP = 5; // Up Via City Loop
// [REMOVED] export const DOWN_VIA_CITY_LOOP = 6; // Down Via City Loop
// [REMOVED] export const UP_VIA_METRO_TUNNEL = 7; // Up Via Metro Tunnel
// [REMOVED] export const DOWN_VIA_METRO_TUNNEL = 8; // Down Via Metro Tunnel
// [REMOVED] export const ALBURY_BRANCH_UP = 9; // Albury Branch Up
// [REMOVED] export const ALBURY_BRANCH_DOWN = 10; // Albury Branch Down
// [REMOVED] export const SHEPPARTON_BRANCH_UP = 11; // Shepparton Branch Up
// [REMOVED] export const SHEPPARTON_BRANCH_DOWN = 12; // Shepparton Branch Down
// [REMOVED] export const ECHUCA_BRANCH_UP = 13; // Echuca Branch Up
// [REMOVED] export const ECHUCA_BRANCH_DOWN = 14; // Echuca Branch Down
// [REMOVED] export const SWAN_HILL_BRANCH_UP = 15; // Swan Hill Branch Up
// [REMOVED] export const SWAN_HILL_BRANCH_DOWN = 16; // Swan Hill Branch Down
// [REMOVED] export const MARYBOROUGH_BRANCH_UP = 17; // Maryborough Branch Up
// [REMOVED] export const MARYBOROUGH_BRANCH_DOWN = 18; // Maryborough Branch Down
// [REMOVED] export const ARARAT_BRANCH_UP = 19; // Ararat Branch Up
// [REMOVED] export const ARARAT_BRANCH_DOWN = 20; // Ararat Branch Down
export const ROUTE_1 = 21; // Route 1
export const ROUTE_2 = 22; // Route 2
export const ROUTE_3 = 23; // Route 3
export const ROUTE_4 = 24; // Route 4
export const ROUTE_5 = 25; // Route 5
export const ROUTE_6 = 26; // Route 6
