export const UP = 1; // Up
export const DOWN = 2; // Down
export const UP_DIRECT = 3; // Up Direct
export const DOWN_DIRECT = 4; // Down Direct
export const UP_VIA_CITY_LOOP = 5; // Up Via City Loop
export const DOWN_VIA_CITY_LOOP = 6; // Down Via City Loop
export const UP_VIA_METRO_TUNNEL = 7; // Up Via Metro Tunnel
export const DOWN_VIA_METRO_TUNNEL = 8; // Down Via Metro Tunnel
export const ALBURY_BRANCH_UP = 9; // Albury Branch Up
export const ALBURY_BRANCH_DOWN = 10; // Albury Branch Down
export const SHEPPARTON_BRANCH_UP = 11; // Shepparton Branch Up
export const SHEPPARTON_BRANCH_DOWN = 12; // Shepparton Branch Down
export const ECHUCA_BRANCH_UP = 13; // Echuca Branch Up
export const ECHUCA_BRANCH_DOWN = 14; // Echuca Branch Down
export const SWAN_HILL_BRANCH_UP = 15; // Swan Hill Branch Up
export const SWAN_HILL_BRANCH_DOWN = 16; // Swan Hill Branch Down
export const MARYBOROUGH_BRANCH_UP = 17; // Maryborough Branch Up
export const MARYBOROUGH_BRANCH_DOWN = 18; // Maryborough Branch Down
export const ARARAT_BRANCH_UP = 19; // Ararat Branch Up
export const ARARAT_BRANCH_DOWN = 20; // Ararat Branch Down
