import { type ParsedStop } from "../../stops/extract-stops-from-tree.js";
import { type Patch } from "../patch.js";
import * as stop from "../../../../src/ids/stop-ids.js";

const regionalPlatforms = {
  [stop.ALBURY]: ["2"],
  [stop.ARARAT]: ["2"],
  [stop.ARDEER]: ["1", "2"],
  [stop.AVENEL]: ["1", "2"],
  [stop.BACCHUS_MARSH]: ["1", "2"],
  [stop.BAIRNSDALE]: ["1"],
  [stop.BALLAN]: ["1", "2"],
  [stop.BALLARAT]: ["1", "2"],
  [stop.BEAUFORT]: ["1"],
  [stop.BENALLA]: ["1"],
  [stop.BENDIGO]: ["1", "2"],
  [stop.BIRREGURRA]: ["1"],
  [stop.BROADFORD]: ["1", "2"],
  [stop.BUNYIP]: ["1", "2"],
  [stop.CAMPERDOWN]: ["1"],
  [stop.CAROLINE_SPRINGS]: ["1", "2"],
  [stop.CASTLEMAINE]: ["1", "2"],
  [stop.CHILTERN]: ["1", "2"],
  [stop.CLARKEFIELD]: ["1", "2"],
  [stop.CLUNES]: ["1"],
  [stop.COBBLEBANK]: ["1", "2"],
  [stop.COLAC]: ["1"],
  [stop.CORIO]: ["1", "2"],
  [stop.CRESWICK]: ["1"],
  [stop.DEER_PARK]: ["1", "2"],
  [stop.DINGEE]: ["1"],
  [stop.DONNYBROOK]: ["1", "2"],
  [stop.DROUIN]: ["1", "2"],
  [stop.EAGLEHAWK]: ["1"],
  [stop.ECHUCA]: ["1"],
  [stop.ELMORE]: ["1"],
  [stop.EPSOM]: ["1"],
  [stop.EUROA]: ["1", "2"],
  [stop.GARFIELD]: ["1", "2"],
  [stop.GEELONG]: ["1", "2", "3"],
  [stop.GISBORNE]: ["1", "2"],
  [stop.GOORNONG]: ["1"],
  [stop.HEATHCOTE_JUNCTION]: ["1", "2"],
  [stop.HUNTLY]: ["1"],
  [stop.KANGAROO_FLAT]: ["1", "2"],
  [stop.KERANG]: ["1"],
  [stop.KILMORE_EAST]: ["1", "2"],
  [stop.KYNETON]: ["1", "2"],
  [stop.LARA]: ["1", "2"],
  [stop.LITTLE_RIVER]: ["1", "2"],
  [stop.LONGWARRY]: ["1", "2"],
  [stop.MACEDON]: ["1", "2"],
  [stop.MALMSBURY]: ["1"],
  [stop.MARSHALL]: ["1", "2"],
  [stop.MARYBOROUGH]: ["1"],
  [stop.MELTON]: ["1", "2"],
  [stop.MOE]: ["1"],
  [stop.MOOROOPNA]: ["1"],
  [stop.MORWELL]: ["1", "2"],
  [stop.MURCHISON_EAST]: ["1"],
  [stop.NAGAMBIE]: ["1"],
  [stop.NAR_NAR_GOON]: ["1", "2"],
  [stop.NORTH_GEELONG]: ["1", "2"],
  [stop.NORTH_SHORE]: ["1", "2"],
  [stop.PYRAMID]: ["1"],
  [stop.RAYWOOD]: ["1"],
  [stop.RIDDELLS_CREEK]: ["1", "2"],
  [stop.ROCHESTER]: ["1"],
  [stop.ROCKBANK]: ["1", "2"],
  [stop.ROSEDALE]: ["1"],
  [stop.SALE]: ["1"],
  [stop.SEYMOUR]: ["1", "2", "3"],
  [stop.SHEPPARTON]: ["1"],
  [stop.SHERWOOD_PARK]: ["1"],
  [stop.SOUTH_GEELONG]: ["1", "2"],
  [stop.SPRINGHURST]: ["1", "2"],
  [stop.STRATFORD]: ["1"],
  [stop.SWAN_HILL]: ["1"],
  [stop.TALBOT]: ["1"],
  [stop.TALLAROOK]: ["1", "2"],
  [stop.TARNEIT]: ["1", "2"],
  [stop.TERANG]: ["1"],
  [stop.TRAFALGAR]: ["1", "2"],
  [stop.TRARALGON]: ["1", "2"],
  [stop.TYNONG]: ["1", "2"],
  [stop.VIOLET_TOWN]: ["1", "2"],
  [stop.WALLAN]: ["1", "2"],
  [stop.WANDONG]: ["1", "2"],
  [stop.WANGARATTA]: ["1"],
  [stop.WARRAGUL]: ["1", "2"],
  [stop.WARRNAMBOOL]: ["1"],
  [stop.WAURN_PONDS]: ["1", "2"],
  [stop.WENDOUREE]: ["1", "2"],
  [stop.WINCHELSEA]: ["1"],
  [stop.WODONGA]: ["1"],
  [stop.WOODEND]: ["1", "2"],
  [stop.WYNDHAM_VALE]: ["1", "2"],
  [stop.YARRAGON]: ["1", "2"],
};

const additionalSuburbanPlatforms = {
  [stop.BERWICK]: [],
  [stop.BROADMEADOWS]: [],
  [stop.CAULFIELD]: [],
  [stop.CLAYTON]: [],
  [stop.CRAIGIEBURN]: [],
  [stop.DANDENONG]: [],
  [stop.ESSENDON]: [],
  [stop.FLINDERS_STREET]: [],
  [stop.FOOTSCRAY]: [],
  [stop.NORTH_MELBOURNE]: [],
  [stop.PAKENHAM]: [],
  [stop.RICHMOND]: [],
  [stop.SOUTHERN_CROSS]: [],
  [stop.SUNBURY]: [],
  [stop.SUNSHINE]: [],
  [stop.WATERGARDENS]: [],
};

export const addRegionalPlatformsPatch: Patch<ParsedStop[]> = (stops) => {
  // TODO: Everything.
  return stops;
};
