import { type ParsedStop } from "../../stops/extract-stops-from-tree.js";
import { type Patch } from "../patch.js";
import * as stop from "../../../../src/ids/stop-ids.js";

const regionalPlatforms = {
  [stop.ALBURY]: [],
  [stop.ARARAT]: [],
  [stop.ARDEER]: [],
  [stop.AVENEL]: [],
  [stop.BACCHUS_MARSH]: [],
  [stop.BAIRNSDALE]: [],
  [stop.BALLAN]: [],
  [stop.BALLARAT]: [],
  [stop.BEAUFORT]: [],
  [stop.BENALLA]: [],
  [stop.BENDIGO]: [],
  [stop.BIRREGURRA]: [],
  [stop.BROADFORD]: [],
  [stop.BUNYIP]: [],
  [stop.CAMPERDOWN]: [],
  [stop.CAROLINE_SPRINGS]: [],
  [stop.CASTLEMAINE]: [],
  [stop.CHILTERN]: [],
  [stop.CLARKEFIELD]: [],
  [stop.CLUNES]: [],
  [stop.COBBLEBANK]: [],
  [stop.COLAC]: [],
  [stop.CORIO]: [],
  [stop.CRESWICK]: [],
  [stop.DEER_PARK]: [],
  [stop.DINGEE]: [],
  [stop.DONNYBROOK]: [],
  [stop.DROUIN]: [],
  [stop.EAGLEHAWK]: [],
  [stop.ECHUCA]: [],
  [stop.ELMORE]: [],
  [stop.EPSOM]: [],
  [stop.EUROA]: [],
  [stop.GARFIELD]: [],
  [stop.GEELONG]: [],
  [stop.GISBORNE]: [],
  [stop.GOORNONG]: [],
  [stop.HEATHCOTE_JUNCTION]: [],
  [stop.HUNTLY]: [],
  [stop.KANGAROO_FLAT]: [],
  [stop.KERANG]: [],
  [stop.KILMORE_EAST]: [],
  [stop.KYNETON]: [],
  [stop.LARA]: [],
  [stop.LITTLE_RIVER]: [],
  [stop.LONGWARRY]: [],
  [stop.MACEDON]: [],
  [stop.MALMSBURY]: [],
  [stop.MARSHALL]: [],
  [stop.MARYBOROUGH]: [],
  [stop.MELTON]: [],
  [stop.MOE]: [],
  [stop.MOOROOPNA]: [],
  [stop.MORWELL]: [],
  [stop.MURCHISON_EAST]: [],
  [stop.NAGAMBIE]: [],
  [stop.NAR_NAR_GOON]: [],
  [stop.NORTH_GEELONG]: [],
  [stop.NORTH_SHORE]: [],
  [stop.PYRAMID]: [],
  [stop.RAYWOOD]: [],
  [stop.RIDDELLS_CREEK]: [],
  [stop.ROCHESTER]: [],
  [stop.ROCKBANK]: [],
  [stop.ROSEDALE]: [],
  [stop.SALE]: [],
  [stop.SEYMOUR]: [],
  [stop.SHEPPARTON]: [],
  [stop.SHERWOOD_PARK]: [],
  [stop.SOUTH_GEELONG]: [],
  [stop.SPRINGHURST]: [],
  [stop.STRATFORD]: [],
  [stop.SWAN_HILL]: [],
  [stop.TALBOT]: [],
  [stop.TALLAROOK]: [],
  [stop.TARNEIT]: [],
  [stop.TERANG]: [],
  [stop.TRAFALGAR]: [],
  [stop.TRARALGON]: [],
  [stop.TYNONG]: [],
  [stop.VIOLET_TOWN]: [],
  [stop.WALLAN]: [],
  [stop.WANDONG]: [],
  [stop.WANGARATTA]: [],
  [stop.WARRAGUL]: [],
  [stop.WARRNAMBOOL]: [],
  [stop.WAURN_PONDS]: [],
  [stop.WENDOUREE]: [],
  [stop.WINCHELSEA]: [],
  [stop.WODONGA]: [],
  [stop.WOODEND]: [],
  [stop.WYNDHAM_VALE]: [],
  [stop.YARRAGON]: [],
};

const additionalSuburbanPlatforms = {
  [stop.BERWICK]: [],
  [stop.BROADMEADOWS]: [],
  [stop.CAULFIELD]: [],
  [stop.CLAYTON]: [],
  [stop.CRAIGIEBURN]: [],
  [stop.DANDENONG]: [],
  [stop.ESSENDON]: [],
  [stop.FLINDERS_STREET]: [],
  [stop.FOOTSCRAY]: [],
  [stop.NORTH_MELBOURNE]: [],
  [stop.PAKENHAM]: [],
  [stop.RICHMOND]: [],
  [stop.SOUTHERN_CROSS]: [],
  [stop.SUNBURY]: [],
  [stop.SUNSHINE]: [],
  [stop.WATERGARDENS]: [],
};

export const addRegionalPlatformsPatch: Patch<ParsedStop[]> = (stops) => {
  // TODO: Everything.
  return stops;
};
