import { type LineConfig } from "corequery";
import * as line from "./line-ids.js";
import * as tag from "./line-tags.js";
import * as stop from "../stops/stop-ids.js";
import { linear } from "./route-builders/linear.js";
import { cityLoop } from "./route-builders/city-loop.js";
import { multi } from "./route-builders/multi.js";
import { metroTunnel } from "./route-builders/metro-tunnel.js";
import { branch } from "./route-builders/branch.js";

export const ALAMEIN: LineConfig = {
  id: line.ALAMEIN,
  name: "Alamein",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "alamein",
  ...cityLoop({
    color: "blue",
    stops: [
      { stopId: stop.ALAMEIN },
      { stopId: stop.ASHBURTON },
      { stopId: stop.BURWOOD },
      { stopId: stop.HARTWELL },
      { stopId: stop.WILLISON },
      { stopId: stop.RIVERSDALE },
      { stopId: stop.CAMBERWELL },
      { stopId: stop.AUBURN },
      { stopId: stop.GLENFERRIE },
      { stopId: stop.HAWTHORN },
      { stopId: stop.BURNLEY },
      { stopId: stop.EAST_RICHMOND },
      { stopId: stop.RICHMOND },
    ],
  }),
};

export const BALLARAT: LineConfig = {
  id: line.BALLARAT,
  name: "Ballarat",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "ballarat",
  ...branch({
    commonName: "Ballarat",
    branchAName: "Ararat",
    branchBName: "Maryborough",
    color: "purple",
    commonStops: [
      { stopId: stop.BALLARAT },
      { stopId: stop.BALLAN },
      { stopId: stop.BACCHUS_MARSH },
      { stopId: stop.MELTON },
      { stopId: stop.COBBLEBANK },
      { stopId: stop.ROCKBANK },
      { stopId: stop.CAROLINE_SPRINGS },
      { stopId: stop.DEER_PARK },
      { stopId: stop.ARDEER },
      { stopId: stop.SUNSHINE },
      { stopId: stop.TOTTENHAM, hidden: true },
      { stopId: stop.WEST_FOOTSCRAY, hidden: true },
      { stopId: stop.MIDDLE_FOOTSCRAY, hidden: true },
      { stopId: stop.FOOTSCRAY },
      { stopId: stop.SOUTH_KENSINGTON, hidden: true },
      { stopId: stop.NORTH_MELBOURNE, hidden: true },
      { stopId: stop.SOUTHERN_CROSS },
    ],
    branchAStops: [
      { stopId: stop.ARARAT },
      { stopId: stop.BEAUFORT },
      { stopId: stop.WENDOUREE },
    ],
    branchBStops: [
      { stopId: stop.MARYBOROUGH },
      { stopId: stop.TALBOT },
      { stopId: stop.CLUNES },
      { stopId: stop.CRESWICK },
    ],
  }),
};

export const BELGRAVE: LineConfig = {
  id: line.BELGRAVE,
  name: "Belgrave",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "belgrave",
  ...cityLoop({
    color: "blue",
    stops: [
      { stopId: stop.BELGRAVE },
      { stopId: stop.TECOMA },
      { stopId: stop.UPWEY },
      { stopId: stop.UPPER_FERNTREE_GULLY },
      { stopId: stop.FERNTREE_GULLY },
      { stopId: stop.BORONIA },
      { stopId: stop.BAYSWATER },
      { stopId: stop.HEATHMONT },
      { stopId: stop.RINGWOOD },
      { stopId: stop.HEATHERDALE },
      { stopId: stop.MITCHAM },
      { stopId: stop.NUNAWADING },
      { stopId: stop.BLACKBURN },
      { stopId: stop.LABURNUM },
      { stopId: stop.BOX_HILL },
      { stopId: stop.UNION },
      { stopId: stop.CHATHAM },
      { stopId: stop.CANTERBURY },
      { stopId: stop.EAST_CAMBERWELL },
      { stopId: stop.CAMBERWELL },
      { stopId: stop.AUBURN },
      { stopId: stop.GLENFERRIE },
      { stopId: stop.HAWTHORN },
      { stopId: stop.BURNLEY },
      { stopId: stop.EAST_RICHMOND },
      { stopId: stop.RICHMOND },
    ],
  }),
};

export const BENDIGO: LineConfig = {
  id: line.BENDIGO,
  name: "Bendigo",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "bendigo",
  ...branch({
    commonName: "Bendigo",
    branchAName: "Echuca",
    branchBName: "Swan Hill",
    color: "purple",
    commonStops: [
      { stopId: stop.BENDIGO },
      { stopId: stop.KANGAROO_FLAT },
      { stopId: stop.CASTLEMAINE },
      { stopId: stop.MALMSBURY },
      { stopId: stop.KYNETON },
      { stopId: stop.WOODEND },
      { stopId: stop.MACEDON },
      { stopId: stop.GISBORNE },
      { stopId: stop.RIDDELLS_CREEK },
      { stopId: stop.CLARKEFIELD },
      { stopId: stop.SUNBURY },
      { stopId: stop.DIGGERS_REST, hidden: true },
      { stopId: stop.WATERGARDENS },
      { stopId: stop.KEILOR_PLAINS, hidden: true },
      { stopId: stop.ST_ALBANS, hidden: true },
      { stopId: stop.GINIFER, hidden: true },
      { stopId: stop.ALBION, hidden: true },
      { stopId: stop.SUNSHINE },
      { stopId: stop.TOTTENHAM, hidden: true },
      { stopId: stop.WEST_FOOTSCRAY, hidden: true },
      { stopId: stop.MIDDLE_FOOTSCRAY, hidden: true },
      { stopId: stop.FOOTSCRAY },
      { stopId: stop.SOUTH_KENSINGTON, hidden: true },
      { stopId: stop.NORTH_MELBOURNE, hidden: true },
      { stopId: stop.SOUTHERN_CROSS },
    ],
    branchAStops: [
      { stopId: stop.ECHUCA },
      { stopId: stop.ROCHESTER },
      { stopId: stop.ELMORE },
      { stopId: stop.GOORNONG },
      { stopId: stop.HUNTLY },
      { stopId: stop.EPSOM },
    ],
    branchBStops: [
      { stopId: stop.SWAN_HILL },
      { stopId: stop.KERANG },
      { stopId: stop.PYRAMID },
      { stopId: stop.DINGEE },
      { stopId: stop.RAYWOOD },
      { stopId: stop.EAGLEHAWK },
    ],
  }),
};

export const CRAIGIEBURN: LineConfig = {
  id: line.CRAIGIEBURN,
  name: "Craigieburn",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "craigieburn",
  ...cityLoop({
    color: "yellow",
    stops: [
      { stopId: stop.CRAIGIEBURN },
      { stopId: stop.ROXBURGH_PARK },
      { stopId: stop.COOLAROO },
      { stopId: stop.BROADMEADOWS },
      { stopId: stop.JACANA },
      { stopId: stop.GLENROY },
      { stopId: stop.OAK_PARK },
      { stopId: stop.PASCOE_VALE },
      { stopId: stop.STRATHMORE },
      { stopId: stop.GLENBERVIE },
      { stopId: stop.ESSENDON },
      { stopId: stop.MOONEE_PONDS },
      { stopId: stop.ASCOT_VALE },
      { stopId: stop.NEWMARKET },
      { stopId: stop.KENSINGTON },
      { stopId: stop.NORTH_MELBOURNE },
    ],
  }),
};

export const CRANBOURNE: LineConfig = {
  id: line.CRANBOURNE,
  name: "Cranbourne",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "cranbourne",
  ...multi({
    items: [
      metroTunnel({
        color: "cyan",
        stops: [
          { stopId: stop.CRANBOURNE },
          { stopId: stop.MERINDA_PARK },
          { stopId: stop.LYNBROOK },
          { stopId: stop.DANDENONG },
          { stopId: stop.YARRAMAN },
          { stopId: stop.NOBLE_PARK },
          { stopId: stop.SANDOWN_PARK },
          { stopId: stop.SPRINGVALE },
          { stopId: stop.WESTALL },
          { stopId: stop.CLAYTON },
          { stopId: stop.HUNTINGDALE },
          { stopId: stop.OAKLEIGH },
          { stopId: stop.HUGHESDALE },
          { stopId: stop.MURRUMBEENA },
          { stopId: stop.CARNEGIE },
          { stopId: stop.CAULFIELD },
          { stopId: stop.MALVERN },
          { stopId: stop.ARMADALE, express: true },
          { stopId: stop.TOORAK, express: true },
          { stopId: stop.HAWKSBURN, express: true },
          { stopId: stop.ANZAC },
          { stopId: stop.TOWN_HALL },
        ],
      }),
      cityLoop({
        color: "cyan",
        stops: [
          { stopId: stop.CRANBOURNE },
          { stopId: stop.MERINDA_PARK },
          { stopId: stop.LYNBROOK },
          { stopId: stop.DANDENONG },
          { stopId: stop.YARRAMAN },
          { stopId: stop.NOBLE_PARK },
          { stopId: stop.SANDOWN_PARK },
          { stopId: stop.SPRINGVALE },
          { stopId: stop.WESTALL },
          { stopId: stop.CLAYTON },
          { stopId: stop.HUNTINGDALE },
          { stopId: stop.OAKLEIGH },
          { stopId: stop.HUGHESDALE },
          { stopId: stop.MURRUMBEENA },
          { stopId: stop.CARNEGIE },
          { stopId: stop.CAULFIELD },
          { stopId: stop.MALVERN },
          { stopId: stop.ARMADALE, express: true },
          { stopId: stop.TOORAK, express: true },
          { stopId: stop.HAWKSBURN, express: true },
          { stopId: stop.SOUTH_YARRA },
          { stopId: stop.RICHMOND },
        ],
      }),
    ],
  }),
};

export const FLEMINGTON_RACECOURSE: LineConfig = {
  id: line.FLEMINGTON_RACECOURSE,
  name: "Flemington Racecourse",
  code: null,
  tags: [tag.SUBURBAN, tag.SPECIAL_EVENTS_ONLY, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "flemingtonracecourse",
  ...cityLoop({
    color: "gray",
    stops: [
      { stopId: stop.FLEMINGTON_RACECOURSE },
      { stopId: stop.SHOWGROUNDS },
      { stopId: stop.NEWMARKET },
      { stopId: stop.KENSINGTON },
      { stopId: stop.NORTH_MELBOURNE },
    ],
  }),
};

export const FRANKSTON: LineConfig = {
  id: line.FRANKSTON,
  name: "Frankston",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "frankston",
  ...cityLoop({
    color: "green",
    stops: [
      { stopId: stop.FRANKSTON },
      { stopId: stop.KANANOOK },
      { stopId: stop.SEAFORD },
      { stopId: stop.CARRUM },
      { stopId: stop.BONBEACH },
      { stopId: stop.CHELSEA },
      { stopId: stop.EDITHVALE },
      { stopId: stop.ASPENDALE },
      { stopId: stop.MORDIALLOC },
      { stopId: stop.PARKDALE },
      { stopId: stop.MENTONE },
      { stopId: stop.CHELTENHAM },
      { stopId: stop.SOUTHLAND },
      { stopId: stop.HIGHETT },
      { stopId: stop.MOORABBIN },
      { stopId: stop.PATTERSON },
      { stopId: stop.BENTLEIGH },
      { stopId: stop.MCKINNON },
      { stopId: stop.ORMOND },
      { stopId: stop.GLEN_HUNTLY },
      { stopId: stop.CAULFIELD },
      { stopId: stop.MALVERN },
      { stopId: stop.ARMADALE },
      { stopId: stop.TOORAK },
      { stopId: stop.HAWKSBURN },
      { stopId: stop.SOUTH_YARRA },
      { stopId: stop.RICHMOND },
    ],
  }),
};

export const GEELONG: LineConfig = {
  id: line.GEELONG,
  name: "Geelong",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "geelong",
  ...linear({
    color: "purple",
    stops: [
      { stopId: stop.WARRNAMBOOL },
      { stopId: stop.SHERWOOD_PARK },
      { stopId: stop.TERANG },
      { stopId: stop.CAMPERDOWN },
      { stopId: stop.COLAC },
      { stopId: stop.BIRREGURRA },
      { stopId: stop.WINCHELSEA },
      { stopId: stop.WAURN_PONDS },
      { stopId: stop.MARSHALL },
      { stopId: stop.SOUTH_GEELONG },
      { stopId: stop.GEELONG },
      { stopId: stop.NORTH_GEELONG },
      { stopId: stop.NORTH_SHORE },
      { stopId: stop.CORIO },
      { stopId: stop.LARA },
      { stopId: stop.LITTLE_RIVER },
      { stopId: stop.WYNDHAM_VALE },
      { stopId: stop.TARNEIT },
      { stopId: stop.DEER_PARK },
      { stopId: stop.ARDEER, express: true },
      { stopId: stop.SUNSHINE },
      { stopId: stop.TOTTENHAM, hidden: true },
      { stopId: stop.WEST_FOOTSCRAY, hidden: true },
      { stopId: stop.MIDDLE_FOOTSCRAY, hidden: true },
      { stopId: stop.FOOTSCRAY },
      { stopId: stop.SOUTH_KENSINGTON, hidden: true },
      { stopId: stop.NORTH_MELBOURNE, hidden: true },
      { stopId: stop.SOUTHERN_CROSS },
    ],
  }),
};

export const GIPPSLAND: LineConfig = {
  id: line.GIPPSLAND,
  name: "Gippsland",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "gippsland",
  ...linear({
    color: "purple",
    stops: [
      { stopId: stop.BAIRNSDALE },
      { stopId: stop.STRATFORD },
      { stopId: stop.SALE },
      { stopId: stop.ROSEDALE },
      { stopId: stop.TRARALGON },
      { stopId: stop.MORWELL },
      { stopId: stop.MOE },
      { stopId: stop.TRAFALGAR },
      { stopId: stop.YARRAGON },
      { stopId: stop.WARRAGUL },
      { stopId: stop.DROUIN },
      { stopId: stop.LONGWARRY },
      { stopId: stop.BUNYIP },
      { stopId: stop.GARFIELD },
      { stopId: stop.TYNONG },
      { stopId: stop.NAR_NAR_GOON },
      { stopId: stop.EAST_PAKENHAM, hidden: true },
      { stopId: stop.PAKENHAM },
      { stopId: stop.CARDINIA_ROAD, hidden: true },
      { stopId: stop.OFFICER, hidden: true },
      { stopId: stop.BEACONSFIELD, hidden: true },
      { stopId: stop.BERWICK },
      { stopId: stop.NARRE_WARREN, hidden: true },
      { stopId: stop.HALLAM, hidden: true },
      { stopId: stop.DANDENONG },
      { stopId: stop.YARRAMAN, hidden: true },
      { stopId: stop.NOBLE_PARK, hidden: true },
      { stopId: stop.SANDOWN_PARK, hidden: true },
      { stopId: stop.SPRINGVALE, hidden: true },
      { stopId: stop.WESTALL, hidden: true },
      { stopId: stop.CLAYTON },
      { stopId: stop.HUNTINGDALE, hidden: true },
      { stopId: stop.OAKLEIGH, hidden: true },
      { stopId: stop.HUGHESDALE, hidden: true },
      { stopId: stop.MURRUMBEENA, hidden: true },
      { stopId: stop.CARNEGIE, hidden: true },
      { stopId: stop.CAULFIELD },
      { stopId: stop.MALVERN, hidden: true },
      { stopId: stop.ARMADALE, hidden: true },
      { stopId: stop.TOORAK, hidden: true },
      { stopId: stop.HAWKSBURN, hidden: true },
      { stopId: stop.SOUTH_YARRA, hidden: true },
      { stopId: stop.RICHMOND },
      { stopId: stop.FLINDERS_STREET },
      { stopId: stop.SOUTHERN_CROSS },
    ],
  }),
};

export const GLEN_WAVERLEY: LineConfig = {
  id: line.GLEN_WAVERLEY,
  name: "Glen Waverley",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "glenwaverley",
  ...cityLoop({
    color: "blue",
    stops: [
      { stopId: stop.GLEN_WAVERLEY },
      { stopId: stop.SYNDAL },
      { stopId: stop.MOUNT_WAVERLEY },
      { stopId: stop.JORDANVILLE },
      { stopId: stop.HOLMESGLEN },
      { stopId: stop.EAST_MALVERN },
      { stopId: stop.DARLING },
      { stopId: stop.GLEN_IRIS },
      { stopId: stop.GARDINER },
      { stopId: stop.TOORONGA },
      { stopId: stop.KOOYONG },
      { stopId: stop.HEYINGTON },
      { stopId: stop.BURNLEY },
      { stopId: stop.EAST_RICHMOND },
      { stopId: stop.RICHMOND },
    ],
  }),
};

export const HURSTBRIDGE: LineConfig = {
  id: line.HURSTBRIDGE,
  name: "Hurstbridge",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "hurstbridge",
  ...cityLoop({
    color: "red",
    stops: [
      { stopId: stop.HURSTBRIDGE },
      { stopId: stop.WATTLE_GLEN },
      { stopId: stop.DIAMOND_CREEK },
      { stopId: stop.ELTHAM },
      { stopId: stop.MONTMORENCY },
      { stopId: stop.GREENSBOROUGH },
      { stopId: stop.WATSONIA },
      { stopId: stop.MACLEOD },
      { stopId: stop.ROSANNA },
      { stopId: stop.HEIDELBERG },
      { stopId: stop.EAGLEMONT },
      { stopId: stop.IVANHOE },
      { stopId: stop.DAREBIN },
      { stopId: stop.ALPHINGTON },
      { stopId: stop.FAIRFIELD },
      { stopId: stop.DENNIS },
      { stopId: stop.WESTGARTH },
      { stopId: stop.CLIFTON_HILL },
      { stopId: stop.VICTORIA_PARK },
      { stopId: stop.COLLINGWOOD },
      { stopId: stop.NORTH_RICHMOND },
      { stopId: stop.WEST_RICHMOND },
      { stopId: stop.JOLIMONT },
    ],
  }),
};

export const LILYDALE: LineConfig = {
  id: line.LILYDALE,
  name: "Lilydale",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "lilydale",
  ...cityLoop({
    color: "blue",
    stops: [
      { stopId: stop.LILYDALE },
      { stopId: stop.MOOROOLBARK },
      { stopId: stop.CROYDON },
      { stopId: stop.RINGWOOD_EAST },
      { stopId: stop.RINGWOOD },
      { stopId: stop.HEATHERDALE },
      { stopId: stop.MITCHAM },
      { stopId: stop.NUNAWADING },
      { stopId: stop.BLACKBURN },
      { stopId: stop.LABURNUM },
      { stopId: stop.BOX_HILL },
      { stopId: stop.UNION },
      { stopId: stop.CHATHAM },
      { stopId: stop.CANTERBURY },
      { stopId: stop.EAST_CAMBERWELL },
      { stopId: stop.CAMBERWELL },
      { stopId: stop.AUBURN },
      { stopId: stop.GLENFERRIE },
      { stopId: stop.HAWTHORN },
      { stopId: stop.BURNLEY },
      { stopId: stop.EAST_RICHMOND },
      { stopId: stop.RICHMOND },
    ],
  }),
};

export const MERNDA: LineConfig = {
  id: line.MERNDA,
  name: "Mernda",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "mernda",
  ...cityLoop({
    color: "red",
    stops: [
      { stopId: stop.MERNDA },
      { stopId: stop.HAWKSTOWE },
      { stopId: stop.MIDDLE_GORGE },
      { stopId: stop.SOUTH_MORANG },
      { stopId: stop.EPPING },
      { stopId: stop.LALOR },
      { stopId: stop.THOMASTOWN },
      { stopId: stop.KEON_PARK },
      { stopId: stop.RUTHVEN },
      { stopId: stop.RESERVOIR },
      { stopId: stop.REGENT },
      { stopId: stop.PRESTON },
      { stopId: stop.BELL },
      { stopId: stop.THORNBURY },
      { stopId: stop.CROXTON },
      { stopId: stop.NORTHCOTE },
      { stopId: stop.MERRI },
      { stopId: stop.RUSHALL },
      { stopId: stop.CLIFTON_HILL },
      { stopId: stop.VICTORIA_PARK },
      { stopId: stop.COLLINGWOOD },
      { stopId: stop.NORTH_RICHMOND },
      { stopId: stop.WEST_RICHMOND },
      { stopId: stop.JOLIMONT },
    ],
  }),
};

export const PAKENHAM: LineConfig = {
  id: line.PAKENHAM,
  name: "Pakenham",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "pakenham",
  ...multi({
    items: [
      metroTunnel({
        color: "cyan",
        stops: [
          { stopId: stop.EAST_PAKENHAM },
          { stopId: stop.PAKENHAM },
          { stopId: stop.CARDINIA_ROAD },
          { stopId: stop.OFFICER },
          { stopId: stop.BEACONSFIELD },
          { stopId: stop.BERWICK },
          { stopId: stop.NARRE_WARREN },
          { stopId: stop.HALLAM },
          { stopId: stop.DANDENONG },
          { stopId: stop.YARRAMAN },
          { stopId: stop.NOBLE_PARK },
          { stopId: stop.SANDOWN_PARK },
          { stopId: stop.SPRINGVALE },
          { stopId: stop.WESTALL },
          { stopId: stop.CLAYTON },
          { stopId: stop.HUNTINGDALE },
          { stopId: stop.OAKLEIGH },
          { stopId: stop.HUGHESDALE },
          { stopId: stop.MURRUMBEENA },
          { stopId: stop.CARNEGIE },
          { stopId: stop.CAULFIELD },
          { stopId: stop.MALVERN },
          { stopId: stop.ARMADALE, express: true },
          { stopId: stop.TOORAK, express: true },
          { stopId: stop.HAWKSBURN, express: true },
          { stopId: stop.ANZAC },
          { stopId: stop.TOWN_HALL },
        ],
      }),
      cityLoop({
        color: "cyan",
        stops: [
          { stopId: stop.EAST_PAKENHAM },
          { stopId: stop.PAKENHAM },
          { stopId: stop.CARDINIA_ROAD },
          { stopId: stop.OFFICER },
          { stopId: stop.BEACONSFIELD },
          { stopId: stop.BERWICK },
          { stopId: stop.NARRE_WARREN },
          { stopId: stop.HALLAM },
          { stopId: stop.DANDENONG },
          { stopId: stop.YARRAMAN },
          { stopId: stop.NOBLE_PARK },
          { stopId: stop.SANDOWN_PARK },
          { stopId: stop.SPRINGVALE },
          { stopId: stop.WESTALL },
          { stopId: stop.CLAYTON },
          { stopId: stop.HUNTINGDALE },
          { stopId: stop.OAKLEIGH },
          { stopId: stop.HUGHESDALE },
          { stopId: stop.MURRUMBEENA },
          { stopId: stop.CARNEGIE },
          { stopId: stop.CAULFIELD },
          { stopId: stop.MALVERN },
          { stopId: stop.ARMADALE, express: true },
          { stopId: stop.TOORAK, express: true },
          { stopId: stop.HAWKSBURN, express: true },
          { stopId: stop.SOUTH_YARRA },
          { stopId: stop.RICHMOND },
        ],
      }),
    ],
  }),
};

export const SANDRINGHAM: LineConfig = {
  id: line.SANDRINGHAM,
  name: "Sandringham",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "sandringham",
  ...linear({
    color: "pink",
    stops: [
      { stopId: stop.SANDRINGHAM },
      { stopId: stop.HAMPTON },
      { stopId: stop.BRIGHTON_BEACH },
      { stopId: stop.MIDDLE_BRIGHTON },
      { stopId: stop.NORTH_BRIGHTON },
      { stopId: stop.GARDENVALE },
      { stopId: stop.ELSTERNWICK },
      { stopId: stop.RIPPONLEA },
      { stopId: stop.BALACLAVA },
      { stopId: stop.WINDSOR },
      { stopId: stop.PRAHRAN },
      { stopId: stop.SOUTH_YARRA },
      { stopId: stop.RICHMOND },
      { stopId: stop.FLINDERS_STREET },
    ],
  }),
};

export const SEYMOUR: LineConfig = {
  id: line.SEYMOUR,
  name: "Seymour",
  code: null,
  tags: [tag.REGIONAL, tag.REGIONAL_GTFS_SUBFEED],
  urlPath: "seymour",
  ...branch({
    commonName: "Seymour",
    branchAName: "Albury",
    branchBName: "Shepparton",
    color: "purple",
    commonStops: [
      { stopId: stop.SEYMOUR },
      { stopId: stop.TALLAROOK },
      { stopId: stop.BROADFORD },
      { stopId: stop.KILMORE_EAST },
      { stopId: stop.WANDONG },
      { stopId: stop.HEATHCOTE_JUNCTION },
      { stopId: stop.WALLAN },
      { stopId: stop.DONNYBROOK },
      { stopId: stop.CRAIGIEBURN },
      { stopId: stop.ROXBURGH_PARK, hidden: true },
      { stopId: stop.COOLAROO, hidden: true },
      { stopId: stop.BROADMEADOWS },
      { stopId: stop.JACANA, hidden: true },
      { stopId: stop.GLENROY, hidden: true },
      { stopId: stop.OAK_PARK, hidden: true },
      { stopId: stop.PASCOE_VALE, hidden: true },
      { stopId: stop.STRATHMORE, hidden: true },
      { stopId: stop.GLENBERVIE, hidden: true },
      { stopId: stop.ESSENDON },
      { stopId: stop.MOONEE_PONDS, hidden: true },
      { stopId: stop.ASCOT_VALE, hidden: true },
      { stopId: stop.NEWMARKET, hidden: true },
      { stopId: stop.KENSINGTON, hidden: true },
      { stopId: stop.NORTH_MELBOURNE },
      { stopId: stop.SOUTHERN_CROSS },
    ],
    branchAStops: [
      { stopId: stop.ALBURY },
      { stopId: stop.WODONGA },
      { stopId: stop.CHILTERN },
      { stopId: stop.SPRINGHURST },
      { stopId: stop.WANGARATTA },
      { stopId: stop.BENALLA },
      { stopId: stop.VIOLET_TOWN },
      { stopId: stop.EUROA },
      { stopId: stop.AVENEL },
    ],
    branchBStops: [
      { stopId: stop.SHEPPARTON },
      { stopId: stop.MOOROOPNA },
      { stopId: stop.MURCHISON_EAST },
      { stopId: stop.NAGAMBIE },
    ],
  }),
};

export const STONY_POINT: LineConfig = {
  id: line.STONY_POINT,
  name: "Stony Point",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "stonypoint",
  ...linear({
    color: "green",
    stops: [
      { stopId: stop.STONY_POINT },
      { stopId: stop.CRIB_POINT },
      { stopId: stop.MORRADOO },
      { stopId: stop.BITTERN },
      { stopId: stop.HASTINGS },
      { stopId: stop.TYABB },
      { stopId: stop.SOMERVILLE },
      { stopId: stop.BAXTER },
      { stopId: stop.LEAWARRA },
      { stopId: stop.FRANKSTON },
    ],
  }),
};

export const SUNBURY: LineConfig = {
  id: line.SUNBURY,
  name: "Sunbury",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "sunbury",
  ...multi({
    items: [
      metroTunnel({
        color: "cyan",
        stops: [
          { stopId: stop.SUNBURY },
          { stopId: stop.DIGGERS_REST },
          { stopId: stop.WATERGARDENS },
          { stopId: stop.KEILOR_PLAINS },
          { stopId: stop.ST_ALBANS },
          { stopId: stop.GINIFER },
          { stopId: stop.ALBION },
          { stopId: stop.SUNSHINE },
          { stopId: stop.TOTTENHAM },
          { stopId: stop.WEST_FOOTSCRAY },
          { stopId: stop.MIDDLE_FOOTSCRAY },
          { stopId: stop.FOOTSCRAY },
          { stopId: stop.ARDEN },
          { stopId: stop.PARKVILLE },
          { stopId: stop.STATE_LIBRARY },
          { stopId: stop.TOWN_HALL },
        ],
      }),
      cityLoop({
        color: "yellow",
        stops: [
          { stopId: stop.SUNBURY },
          { stopId: stop.DIGGERS_REST },
          { stopId: stop.WATERGARDENS },
          { stopId: stop.KEILOR_PLAINS },
          { stopId: stop.ST_ALBANS },
          { stopId: stop.GINIFER },
          { stopId: stop.ALBION },
          { stopId: stop.SUNSHINE },
          { stopId: stop.TOTTENHAM },
          { stopId: stop.WEST_FOOTSCRAY },
          { stopId: stop.MIDDLE_FOOTSCRAY },
          { stopId: stop.FOOTSCRAY },
          { stopId: stop.SOUTH_KENSINGTON, express: true },
          { stopId: stop.NORTH_MELBOURNE },
        ],
      }),
    ],
  }),
};

export const UPFIELD: LineConfig = {
  id: line.UPFIELD,
  name: "Upfield",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "upfield",
  ...cityLoop({
    color: "yellow",
    stops: [
      { stopId: stop.UPFIELD },
      { stopId: stop.GOWRIE },
      { stopId: stop.FAWKNER },
      { stopId: stop.MERLYNSTON },
      { stopId: stop.BATMAN },
      { stopId: stop.COBURG },
      { stopId: stop.MORELAND },
      { stopId: stop.ANSTEY },
      { stopId: stop.BRUNSWICK },
      { stopId: stop.JEWELL },
      { stopId: stop.ROYAL_PARK },
      { stopId: stop.FLEMINGTON_BRIDGE },
      { stopId: stop.MACAULAY },
      { stopId: stop.NORTH_MELBOURNE },
    ],
  }),
};

export const WERRIBEE: LineConfig = {
  id: line.WERRIBEE,
  name: "Werribee",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "werribee",
  ...linear({
    color: "green",
    stops: [
      { stopId: stop.WERRIBEE },
      { stopId: stop.HOPPERS_CROSSING },
      { stopId: stop.WILLIAMS_LANDING },
      { stopId: stop.AIRCRAFT },
      { stopId: stop.LAVERTON },
      { stopId: stop.WESTONA },
      { stopId: stop.ALTONA },
      { stopId: stop.SEAHOLME },
      { stopId: stop.NEWPORT },
      { stopId: stop.SPOTSWOOD },
      { stopId: stop.YARRAVILLE },
      { stopId: stop.SEDDON },
      { stopId: stop.FOOTSCRAY },
      { stopId: stop.SOUTH_KENSINGTON },
      { stopId: stop.NORTH_MELBOURNE },
      { stopId: stop.SOUTHERN_CROSS },
      { stopId: stop.FLINDERS_STREET },
    ],
  }),
};

export const WILLIAMSTOWN: LineConfig = {
  id: line.WILLIAMSTOWN,
  name: "Williamstown",
  code: null,
  tags: [tag.SUBURBAN_FULL_TIME, tag.SUBURBAN_GTFS_SUBFEED],
  urlPath: "williamstown",
  ...linear({
    color: "green",
    stops: [
      { stopId: stop.WILLIAMSTOWN },
      { stopId: stop.WILLIAMSTOWN_BEACH },
      { stopId: stop.NORTH_WILLIAMSTOWN },
      { stopId: stop.NEWPORT },
      { stopId: stop.SPOTSWOOD },
      { stopId: stop.YARRAVILLE },
      { stopId: stop.SEDDON },
      { stopId: stop.FOOTSCRAY },
      { stopId: stop.SOUTH_KENSINGTON },
      { stopId: stop.NORTH_MELBOURNE },
      { stopId: stop.SOUTHERN_CROSS },
      { stopId: stop.FLINDERS_STREET },
    ],
  }),
};
